const hbss = {
  pages: [
    {
      '1Depth': '팝업',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/hbss/etc',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': 'HBSS',
      '2Depth': '배송지등록',
      '3Depth': '받은 선물 보기',
      '4Depth': 'step1',
      FILE: '/hbss/delivery/DeliveryStep1',
      PATH: '/hbss/delivery/verify',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'step2',
      FILE: '/hbss/delivery/DeliveryStep2',
      PATH: '/hbss/delivery/register',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'step3',
      FILE: '/hbss/delivery/DeliveryStep3',
      PATH: '/hbss/delivery/confirm',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'step4',
      FILE: '/hbss/delivery/DeliveryStep4',
      PATH: '/hbss/delivery/complete',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'H.point 전환',
      '3Depth': '교환신청',
      '4Depth': '',
      FILE: '/hbss/hpoint/HpointApply',
      PATH: '/hbss/hpoint/apply',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '교환완료',
      '4Depth': '',
      FILE: '/hbss/hpoint/HpointComplete',
      PATH: '/hbss/hpoint/complete',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '모바일 정보확인',
      '3Depth': '현대백화점 명절선물 배송지 입력',
      '4Depth': 'step1',
      FILE: '/hbss/mobile/check/MobileCheckStep1',
      PATH: '/hbss/mobile/check/verify',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'step2',
      FILE: '/hbss/mobile/check/MobileCheckStep2',
      PATH: '/hbss/mobile/check/register',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'step3',
      FILE: '/hbss/mobile/check/MobileCheckStep3',
      PATH: '	/hbss/mobile/check/confirm',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'step4',
      FILE: '/hbss/mobile/check/MobileCheckStep4',
      PATH: '	/hbss/mobile/check/complete',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 배송 예정일 선택 (L)',
      '4Depth': '',
      FILE: '/hbss/components/DeliveryDateSelectDialog',
      PATH: '/hbss/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 마케팅 활용을 위한 개인정보 수집 · 이용 동의 (D)',
      '4Depth': '',
      FILE: '/hbss/components/AgreeDrawer',
      PATH: '/hbss/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '모바일 비대면 접수',
      '3Depth': '현대백화점 명절 배송 접수',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '개인정보제공 동의 약관동의',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '보내시는 분 정보 입력',
      '4Depth': 'step1',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'step2',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'step3',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'step4',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'step5',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '현장 배송 접수',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '배송조회',
      '3Depth': '본인 인증',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '보내시는 분 배송조회',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 배송정보 자세히 보기 (L)',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '받으시는 분 배송조회',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 배송정보 자세히 보기 (L)',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '특별판매행사접수 모바일정보 확인',
      '3Depth': '인증',
      '4Depth': '',
      FILE: '/hbss/special/SpecialStepVerify',
      PATH: '/hbss/special/verify',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '메인',
      '4Depth': '',
      FILE: '/hbss/special/SpecialStepMain',
      PATH: '/hbss/special',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '개인정보제공 동의',
      '4Depth': '',
      FILE: '/hbss/special/SpecialStepAgree',
      PATH: '/hbss/special/agree',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': 'step1. 정보입력',
      '4Depth': '',
      FILE: '/hbss/special/SpecialStep1',
      PATH: '/hbss/special/register',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 택배 발송일 선택 (L)',
      '4Depth': '',
      FILE: '/hbss/components/DeliveryDateSelectDialog',
      PATH: '/hbss/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 감사 상품 목록 (L)',
      '4Depth': '',
      FILE: '/hbss/components/ThanksProdListDialog',
      PATH: '/hbss/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': 'step2. 정보확인',
      '4Depth': '',
      FILE: '/hbss/special/SpecialStep2',
      PATH: '/hbss/special/confirm',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': 'step3. 완료',
      '4Depth': '',
      FILE: '/hbss/special/SpecialStep3',
      PATH: '/hbss/special/complete',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },

    {
      '1Depth': '',
      '2Depth': '더현대 투홈, 수취인 배송조회',
      '3Depth': '본인 인증',
      '4Depth': '',
      FILE: '/hbss/tohome/TohomeVerify',
      PATH: '/hbss/tohome',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 배송조회 (L)',
      '4Depth': '',
      FILE: '/hbss/components/DeliveryTraceDialog',
      PATH: '/hbss/etc',
      작업자: '채은미',
      상태: 'progress',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'ALOA 배송조회',
      '3Depth': '현대백화점 배송 안내',
      '4Depth': '',
      FILE: '/hbss/aloa/AloaDeliveryInfo',
      PATH: '/hbss/aloa',
      작업자: '채은미',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
  ],
} as const;

export default hbss;
