const mypage = {
  pages: [
    {
      '1Depth': '나의활동 - 팝업모음집',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/activity/etc',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '나의 활동',
      '2Depth': '상품 리뷰',
      '3Depth': '목록',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/activity/reviews/product',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '리뷰 없음',
      FILE: '',
      PATH: '/mypage/activity/reviews/product?nodata',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '상품 리뷰 작성',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/activity/reviews/product/write',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '상품 리뷰 수정',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/activity/reviews/product/edit',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '매장 리뷰',
      '3Depth': '목록',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/case?type=myOrder',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '매장 리뷰 작성',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/case?type=myOrder',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '매장 리뷰 수정',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/case?type=myOrder',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '쇼핑 알림',
      '3Depth': '목록',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/activity/alram',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '알림 없음',
      FILE: '',
      PATH: '/mypage/activity/alram?nodata',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '알림 관리',
      '4Depth': '내가 팔로우한 LIVE 알림 관리',
      FILE: '',
      PATH: '/mypage/order/case?type=myOrder',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '채널별 LIVE 알림 관리',
      FILE: '',
      PATH: '/mypage/order/case?type=myOrder',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '최근 본 상품',
      '3Depth': '목록',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/activity/recent',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '없음',
      FILE: '',
      PATH: '/mypage/activity/recent?nodata',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '나의 문의내역',
      '3Depth': '상품 Q&A',
      '4Depth': '목록',
      FILE: '',
      PATH: '/mypage/activity/inquiries',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '목록 없음',
      FILE: '',
      PATH: '/mypage/activity/inquiries?nodata',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '1:1 문의',
      '4Depth': '목록',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '목록 없음',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'VIP 마일리지',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/activity/vip',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '나의 이벤트 참여내역',
      '3Depth': '목록',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/activity/event/history',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '목록 없음',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/activity/event/history?nodata',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '제세공과금 안내',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/activity/event/taxinfo',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '출석체크 전월 기록 확인하기',
      '4Depth': '전월 출석이력 없는 경우',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '누적 당첨 경품있는 유형',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '나의정보 - 팝업모음집',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/info/etc',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '나의 정보',
      '2Depth': '회원정보 변경',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/info/change',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '배송지 관리',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/activity/reviews/product',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '배송지 없음',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/activity/reviews/product',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '나의 맞춤정보 관리',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/info/preferences',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '로그인 기록',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/info/loginlog',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '간편계정 연결관리',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/activity/reviews/product',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '임직원 인증',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/info/auth',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '인증완료',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/info/auth?complete',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '개인정보 이용현황',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/info/privacyinfo',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '개인정보 수집 및 이용',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/info/privacyinfo/policy',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '개인정보 처리 위탁',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/info/privacyinfo/outsourcing',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '차량 등록 관리',
      '3Depth': '등록차량 없음',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/info/carregister',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '등록차량 있음',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/info/carregister',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '회원탈퇴',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/info/leave',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '비밀번호 확인',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/info/password',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '본인인증',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/activity/reviews/product',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },

    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },

    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '주문/배송',
      '2Depth': 'Full CASE',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/case?type=myOrder',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '플래그 CASE',
      '3Depth': '주문 플래그',
      '4Depth': '',
      FILE: '/widgets/product/OrderStatusFlag',
      PATH: '/mypage/order/case?type=flag',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '비대면 반품',
      '4Depth': '',
      FILE: '/mypage/claims/components/ReturnStatusFlag',
      PATH: '/mypage/order/case?type=returnFlag',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '버튼 CASE',
      '3Depth': '공통',
      '4Depth': '',
      FILE: '/widgets/product/OrderStatusBtns',
      PATH: '/mypage/order/btns?type=common',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '스토어픽',
      '4Depth': '',
      FILE: '/widgets/product/OrderStatusBtns',
      PATH: '/mypage/order/btns?type=storepick',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '선물하기',
      '4Depth': '',
      FILE: '/widgets/product/OrderStatusBtns',
      PATH: '/mypage/order/btns?type=gift',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '방문픽업',
      '4Depth': '',
      FILE: '/widgets/product/OrderStatusBtns',
      PATH: '/mypage/order/btns?type=pickup',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '체험단/0원상품',
      '4Depth': '',
      FILE: '/widgets/product/OrderStatusBtns',
      PATH: '/mypage/order/btns?type=experience',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '기타',
      '4Depth': '',
      FILE: '/widgets/product/OrderStatusBtns',
      PATH: '/mypage/order/btns?type=etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '취소 가능 케이스',
      '4Depth': '',
      FILE: '/widgets/product/OrderStatusBtns',
      PATH: '/mypage/order/btns?type=cancelable',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '문화센터 예외',
      '4Depth': '',
      FILE: '/widgets/product/OrderStatusBtns',
      PATH: '/mypage/order/btns?type=culture',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '영역별 CASE',
      '3Depth': '결제수단 & 승인내역',
      '4Depth': '',
      FILE: '/mypage/order/detail/PaymentApprovalInfo',
      PATH: '/mypage/order/case?type=paymentApproval',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '결제정보',
      '4Depth': '',
      FILE: '/mypage/order/detail/PaymentInfo',
      PATH: '/mypage/order/case?type=payment',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '환불 계좌 안내',
      '4Depth': '',
      FILE: '/mypage/claims/components/RefundAccountInfo',
      PATH: '/mypage/order/case?type=returnAccount',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '사은품',
      '4Depth': '',
      FILE: '/mypage/claims/components/CheckGiftBox',
      PATH: '/mypage/order/case?type=gift',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '목록',
      '3Depth': '',
      '4Depth': '',
      FILE: '/mypage/order/list/OrderDeliveryList',
      PATH: '/mypage/order/list',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '결과없음',
      '4Depth': '',
      FILE: '/mypage/order/list/OrderDeliveryList',
      PATH: '/mypage/order/list?nodata',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '영수증',
      '4Depth': '',
      FILE: 'mypage/order/receipt/OrderReceipt',
      PATH: '/mypage/order/receipt',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 검색설정 (D)',
      '4Depth': '',
      FILE: '/widgets/order/TagFilterSetDrawer',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 택배배송조회 (L)',
      '4Depth': '',
      FILE: '/order/components/DeliveryStatusDialog',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 반품교환선택 (D)',
      '4Depth': '',
      FILE: '/mypage/order/ReturnOrExchangeDrawer',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ NCP 카드영수증 (L)',
      '4Depth': '',
      FILE: '/mypage/order/receipt/components/CardReceiptDialog',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ H-Pay 카드영수증 (L)',
      '4Depth': '',
      FILE: '/mypage/order/receipt/components/CardReceiptDialog',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 현금영수증 (L)',
      '4Depth': '',
      FILE: '/mypage/order/receipt/components/CashReceiptDialog',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 구매확정 (D)',
      '4Depth': '',
      FILE: '/mypage/order/components/BuyConfirmedDrawer',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 문의하기 (D)',
      '4Depth': '',
      FILE: '/mypage/order/components/InquirydDrawer',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '상세',
      '3Depth': '일반',
      '4Depth': '',
      FILE: '/mypage/order/detail/OrderDeliveryDetail',
      PATH: '/mypage/order/detail/normal',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 배송지 변경 (L)',
      '4Depth': '',
      FILE: '/order/components/DeliveryChangeDialog',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 배송지 요청 사항 변경 (L)',
      '4Depth': '',
      FILE: '/widgets/order/DeliveryRequestEditDialog',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 결제수단 변경 (L)',
      '4Depth': '',
      FILE: '/order/components/PaymentChangeDialog',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 결제정보 상세 (L)',
      '4Depth': '',
      FILE: '/order/components/PaymentInfoDialog',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '멀티',
      FILE: '/mypage/order/detail/OrderDeliveryDetail',
      PATH: '/mypage/order/detail/normal?multi',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '스토어픽',
      '4Depth': '',
      FILE: '/mypage/order/detail/OrderDeliveryStorePickDetail',
      PATH: '/mypage/order/detail/storepick',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 위치보기 (L)',
      '4Depth': '',
      FILE: '/widgets/order/LocationDialog',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 교환권 조회 (L)',
      '4Depth': '',
      FILE: '/mypage/order/components/ExchangeItemDrawer',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 사용안내 (D)',
      '4Depth': '',
      FILE: '/mypage/order/components/UseGuideDrawer',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '선물하기',
      '4Depth': '',
      FILE: '/mypage/order/detail/OrderDeliveryGiftDetail',
      PATH: '/mypage/order/detail/gift',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '멀티',
      FILE: '/mypage/order/detail/OrderDeliveryGiftDetail',
      PATH: '/mypage/order/detail/gift?multi',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '직구',
      '4Depth': '',
      FILE: '/mypage/order/detail/OrderDeliveryDetailGlobal',
      PATH: '/mypage/order/detail/global',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '역직구 EMS',
      '4Depth': '',
      FILE: '/mypage/order/detail/OrderDeliveryDetailGlobal',
      PATH: '/mypage/order/detail/global?ems',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '렌탈',
      '4Depth': '',
      FILE: '/mypage/order/detail/OrderDeliveryDetailRental',
      PATH: '/mypage/order/detail/rental',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '상담 후 결제',
      FILE: '/mypage/order/detail/OrderDeliveryDetailRental',
      PATH: '/mypage/order/detail/rental?case1',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '상담 후 결제_결제 후',
      FILE: '/mypage/order/detail/OrderDeliveryDetailRental',
      PATH: '/mypage/order/detail/rental?case2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 요청사항 변경 (D)',
      '4Depth': '',
      FILE: '/mypage/order/component/RequestChangeDrawer',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '명절배송',
      '4Depth': '',
      FILE: '/mypage/order/detail/OrderDeliveryDetailHoliday',
      PATH: '/mypage/order/detail/holiday',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '체험단',
      '4Depth': '',
      FILE: '/mypage/order/detail/OrderDeliveryDetailExperience',
      PATH: '/mypage/order/detail/experience',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '문화센터',
      '4Depth': '',
      FILE: '/mypage/order/detail/OrderDeliveryCultureDetail',
      PATH: '/mypage/order/detail/culture',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '방문픽업',
      '4Depth': '',
      FILE: '/mypage/order/detail/OrderDeliveryStorePickDetail',
      PATH: '/mypage/order/detail/visit',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 수령자 편집 (L)',
      '4Depth': '',
      FILE: '/mypage/order/component/RecipientInfoEditDrawer',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '사은품 - 0원상품',
      '4Depth': '',
      FILE: '/mypage/order/detail/OrderDeliveryDetailPurchaseGift',
      PATH: '/mypage/order/detail/purchasegift',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '옴니결제',
      '4Depth': '',
      FILE: '/mypage/order/detail/OrderDeliveryDetailOmni',
      PATH: '/mypage/order/detail/omni',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '기타',
      '3Depth': '샤넬 & 회원 (L)',
      '4Depth': '',
      FILE: '/mypage/order/components/ChanelBuyDialog',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '샤넬 & 회원 Full (L)',
      '4Depth': '',
      FILE: '/mypage/order/components/ChanelBuyDialog',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '클레임',
      '2Depth': '목록',
      '3Depth': '',
      '4Depth': '',
      FILE: '/mypage/claims/cancel/list/CancelList',
      PATH: '/mypage/claims/cancel/list',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '결과없음',
      '4Depth': '',
      FILE: '/mypage/claims/cancel/list/CancelList',
      PATH: '/mypage/claims/cancel/list?nodata',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '상세',
      '3Depth': '',
      '4Depth': '',
      FILE: '/mypage/claims/cancel/detail/CancelDetail',
      PATH: '/mypage/claims/cancel/detail',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 이미지 크게보기(L)',
      '4Depth': '',
      FILE: '/mypage/order/components/ChanelBuyDialog',
      PATH: '/mypage/claims/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 주문 취소 완료 (L)',
      '4Depth': '',
      FILE: '/mypage/claims/cancel/list/CancleCompleteDialog',
      PATH: '/mypage/claims/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '취소',
      '2Depth': '주문 취소 신청',
      '3Depth': '일반',
      '4Depth': '',
      FILE: '/mypage/claims/cancel/apply/CancelApply',
      PATH: '/mypage/claims/cancel/apply',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 추가 결제 안내 (L)',
      '4Depth': '',
      FILE: '/mypage/claims/cancel/components/ExtraPayInfoDialog',
      PATH: '/mypage/claims/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 추가 결제 (L)',
      '4Depth': '',
      FILE: '/mypage/claims/cancel/components/NeedExtraPayDialog',
      PATH: '/mypage/claims/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 추가결제필요 안내 (L)',
      '4Depth': '',
      FILE: '/mypage/claims/cancel/components/NeedExtraPayInfoDialog',
      PATH: '/mypage/claims/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 환불 계좌 등록/수정 (L)',
      '4Depth': '',
      FILE: '/mypage/claims/components/RefundAccountDialog',
      PATH: '/mypage/claims/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 개인정보수집 및 이용안내 (D)',
      '4Depth': '',
      FILE: '/mypage/claims/cancel/components/PrivacyInfoDrawer',
      PATH: '/mypage/claims/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 취소 상세 보기 (L)',
      '4Depth': '',
      FILE: '/mypage/claims/cancel/components/CancelDetailDialog',
      PATH: '/mypage/claims/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '멀티',
      '4Depth': '',
      FILE: '/mypage/claims/cancel/apply/CancelApply',
      PATH: '/mypage/claims/cancel/apply?multi',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '반품',
      '2Depth': '접수',
      '3Depth': '1단계',
      '4Depth': '',
      FILE: '/mypage/claims/return/ReturnApplyStep1',
      PATH: '/mypage/claims/return/step1',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '2단계',
      '4Depth': '',
      FILE: '/mypage/claims/return/ReturnApplyStep2',
      PATH: '/mypage/claims/return/step2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '예상 환불정보 금액 마이너스',
      FILE: '/mypage/claims/return/ReturnApplyStep2',
      PATH: '/mypage/claims/return/step2?case2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '반품배송비-무료 반품 프로모션 적용 시',
      FILE: '/mypage/claims/return/ReturnApplyStep2',
      PATH: '/mypage/claims/return/step2?case3',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '3단계',
      '4Depth': '택배',
      FILE: '/mypage/claims/return/ReturnApplyStep3',
      PATH: '/mypage/claims/return/step3',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '매장',
      FILE: '/mypage/claims/return/ReturnApplyStep3',
      PATH: '/mypage/claims/return/step3?store',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 반품 상세 보기 (L)',
      '4Depth': '',
      FILE: '/mypage/claims/return/components/ReturnDetailDialog',
      PATH: '/mypage/claims/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ H.Point 결제 필요 안내 (L)',
      '4Depth': '',
      FILE: '/mypage/claims/components/HpointNeedPayDialog',
      PATH: '/mypage/claims/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '교환',
      '2Depth': '접수',
      '3Depth': '1단계',
      '4Depth': '단독',
      FILE: '/mypage/claims/exchange/ExchangeApplyStep1',
      PATH: '/mypage/claims/exchange/step1',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '멀티',
      FILE: '/mypage/claims/exchange/ExchangeApplyStep1',
      PATH: '/mypage/claims/exchange/step1?multi',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '2단계',
      '4Depth': '',
      FILE: '/mypage/claims/exchange/ExchangeApplyStep2',
      PATH: '/mypage/claims/exchange/step2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '3단계',
      '4Depth': '단일',
      FILE: '/mypage/claims/exchange/ExchangeApplyStep3',
      PATH: '/mypage/claims/exchange/step3',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '멀티',
      FILE: '/mypage/claims/exchange/ExchangeApplyStep3',
      PATH: '/mypage/claims/exchange/step3?multi',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 교환 상세 보기 (L)',
      '4Depth': '',
      FILE: '/mypage/claims/exchange/components/ExchangeDetailDialog',
      PATH: '/mypage/claims/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '비대면 반품',
      '2Depth': '목록',
      '3Depth': '',
      '4Depth': '',
      FILE: '/mypage/claims/return/remote/list/RemoteReturnList',
      PATH: '/mypage/claims/return/remote/list',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '결과없음',
      '4Depth': '',
      FILE: '/mypage/claims/return/remote/list/RemoteReturnList',
      PATH: '/mypage/claims/return/remote/list?nodata',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '상세',
      '3Depth': '',
      '4Depth': '',
      FILE: '/mypage/claims/return/remote/detail/RemoteReturnDetail',
      PATH: '/mypage/claims/return/remote/detail',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '과거 주문내역',
      '2Depth': '메인',
      '3Depth': '',
      '4Depth': '',
      FILE: '/mypage/order/history/OrderHistory',
      PATH: '/mypage/order/history',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '더현대닷컴 인증(과거)',
      '4Depth': '일반/통합회원',
      FILE: '/mypage/order/history/thehyundai/TheHyundaiOrderHistory',
      PATH: '/mypage/order/history/thehyundai',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '투홈 인증(과거)',
      '4Depth': '',
      FILE: '/mypage/order/history/tohome/TohomeOrderHistory',
      PATH: '/mypage/order/history/tohome',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '비로그인',
      '4Depth': '더현대',
      FILE: '/mypage/order/history/guest/GuestOrderHistory',
      PATH: '/mypage/order/history/guest',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 과거주문내역 문의하기 (L)',
      '4Depth': '',
      FILE: '/mypage/order/history/components/OrderHistoryDialog',
      PATH: '/mypage/claims/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-01',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '쇼핑혜택',
      '2Depth': '마이바우처',
      '3Depth': '바우처',
      '4Depth': '사용가능',
      FILE: '/mypage/myvoucher/MyVoucher',
      PATH: '/mypage/voucher',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '사용완료/만료/취소',
      FILE: '/mypage/myvoucher/MyVoucher',
      PATH: '/mypage/voucher?tab2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '2025-08-08',
      비고: '정렬 삭제',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'Nodata',
      FILE: '/mypage/myvoucher/MyVoucher',
      PATH: '/mypage/voucher?nodata',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 바우처 사용하기 (D)',
      FILE: '/mypage/myvoucher/UseVoucherDrawer',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 직원확인 하기-아이체크 방식 (D)',
      FILE: '/mypage/myvoucher/EmployeeCheckDrawer',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 직원확인 하기-아이체크 방식+수량선택 (D)',
      FILE: '/mypage/myvoucher/EmployeeCheckDrawer',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 쿠폰 비밀번호 입력: 인증키 방식 (D)',
      FILE: '/mypage/myvoucher/CouponPasswordDrawer',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 쿠폰 비밀번호 입력: 인증키 방식+수량선택 (D)',
      FILE: '/mypage/myvoucher/CouponPasswordDrawer',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'H.Point',
      '3Depth': '메인',
      '4Depth': '',
      FILE: '/mypage/point/HPointMain',
      PATH: '/mypage/hpoint',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '2025-08-08',
      비고: '총갯수 위치변경',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'NoData',
      FILE: '/mypage/point/HPointMain',
      PATH: '/mypage/hpoint?nodata',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '소멸예정 포인트',
      '4Depth': '',
      FILE: '/mypage/point/HPointExpiring',
      PATH: '/mypage/hpoint/expiring',
      작업자: '채은미',
      상태: 'removed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '삭제됨',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'NoData',
      FILE: '/mypage/point/HPointExpiring',
      PATH: '/mypage/hpoint/expiring?nodata',
      작업자: '채은미',
      상태: 'removed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '삭제됨',
    },
    {
      '1Depth': '',
      '2Depth': 'RSVP 포인트',
      '3Depth': '메인',
      '4Depth': '',
      FILE: '/mypage/point/RsvpMain',
      PATH: '/mypage/rsvp',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '2025-08-08',
      비고: '총갯수 위치변경',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'Nodata',
      FILE: '/mypage/point/RsvpMain',
      PATH: '/mypage/rsvp?nodata',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '소멸예정 포인트',
      '4Depth': '',
      FILE: '/mypage/point/RsvpExpiring',
      PATH: '/mypage/rsvp/expiring',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'Nodata',
      FILE: '/mypage/point/RsvpExpiring',
      PATH: '/mypage/rsvp/expiring?nodata',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '예치금',
      '3Depth': '메인',
      '4Depth': '',
      FILE: '/mypage/deposit/DepositMain',
      PATH: '/mypage/deposit',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'noData',
      FILE: '/mypage/deposit/DepositMain',
      PATH: '/mypage/deposit?nodata',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'HiHi 멤버십 관리',
      '3Depth': '[HiHi 멤버십 미가입자]',
      '4Depth': '',
      FILE: '/mypage/membership/MembershipInfo',
      PATH: '/mypage/membership/manage/info',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[HiHi 멤버십 가입 후 메인]',
      '4Depth': '이용권 변경 시',
      FILE: '/mypage/membership/MemberShipManage',
      PATH: '/mypage/membership/manage',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '해지 예약시',
      FILE: '/mypage/membership/MemberShipManage',
      PATH: '/mypage/membership/manage?case2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '멤버십 결제 현황',
      '4Depth': '멤버십 이용중',
      FILE: '/mypage/membership/PaymentStatus',
      PATH: '/mypage/membership/manage/payment',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '해지 예약중_이용기간 남음',
      FILE: '/mypage/membership/PaymentStatus',
      PATH: '/mypage/membership/manage/payment?case2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '이용 중단- 미납 3회차까지',
      FILE: '/mypage/membership/payment/PaymentStatus',
      PATH: '/mypage/membership/manage/payment?case3',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 결제수단 변경 (L)',
      FILE: '/mypage/membership/payment/PaymentChangeDialog',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '멤버십 변경 신청',
      '4Depth': '프라임 변경 시',
      FILE: '/mypage/membership/change/ChangePrime',
      PATH: '/mypage/membership/manage/change?status=status1',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '플러스 변경 시',
      FILE: '/mypage/membership/change/ChangePlus',
      PATH: '/mypage/membership/manage/change?status=status2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 정기배송 상품 변경 신청 (L)',
      FILE: '/mypage/membership/change/ProductChangeDialog',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '2025-07-28',
      비고: '설계변경반영',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '이용 내역 상세보기',
      '4Depth': '',
      FILE: '/mypage/membership/MembershipHistory',
      PATH: '/mypage/membership/manage/history',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'HiHi 멤버십 가입',
      '3Depth': '[프라임 선택 시]',
      '4Depth': '',
      FILE: '/mypage/membership/MembershipJoin',
      PATH: '/mypage/membership/join',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 가입 완료 (L)',
      '4Depth': '',
      FILE: '/mypage/membership/components/JoinCompleteDialog',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 가입 실패 (L)',
      '4Depth': '',
      FILE: '/mypage/membership/components/JoinFailDialog',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'HiHi 멤버십 해지',
      '3Depth': '[플러스 이용 해지하기 선택 시 플러스 혜택]',
      '4Depth': '',
      FILE: '/mypage/membership/cancel/CancelStep1',
      PATH: '/mypage/membership/cancel?status=status1&type=plus',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[프라임 이용 해지하기 선택 시 프라임 혜택]',
      '4Depth': '',
      FILE: '/mypage/membership/cancel/CancelStep1',
      PATH: '/mypage/membership/cancel?status=status1&type=prime',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[해지하기 선택 시]',
      '4Depth': '',
      FILE: '/mypage/membership/CancelStep2',
      PATH: '/mypage/membership/cancel?status=status2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '직접 입력 메시지 등록',
      FILE: '/mypage/membership/cancel/CancelReasonDrawer',
      PATH: '/mypage/membership/cancel?status=status2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 해지 완료 (L)',
      '4Depth': '',
      FILE: '/mypage/membership/cancel/CancelCompleteDialog',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '클럽',
      '3Depth': '[case1. 클럽 미가입]',
      '4Depth': '',
      FILE: '/mypage/club/ClubMain',
      PATH: '/mypage/club',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[case2. 클럽 가입]',
      '4Depth': '',
      FILE: '/mypage/club/ClubMain',
      PATH: '/mypage/club?case2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[case3. 클럽 가입불가]',
      '4Depth': '',
      FILE: '/mypage/club/ClubMain',
      PATH: '/mypage/club?case3',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '마이클럽',
      '3Depth': '클럽뷰티',
      '4Depth': '가입 현황',
      FILE: '/mypage/club/myclub/MyClubMain',
      PATH: '/mypage/club/myclub',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '가입',
      FILE: '/mypage/club/myclub/MyClubJoin',
      PATH: '/mypage/club/myclub/join?club=beauty',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '관심정보 수정',
      FILE: '/mypage/club/myclub/MyClubEdit',
      PATH: '/mypage/club/myclub/edit?club=beauty',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽맘스',
      '4Depth': '가입 현황 (작성가능한리뷰 없음 case)',
      FILE: '/mypage/club/myclub/MyClubMain',
      PATH: '/mypage/club/myclub?club=moms',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '가입',
      FILE: '/mypage/club/myclub/MyClubJoin',
      PATH: '/mypage/club/myclub/join?club=moms',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '관심정보 수정',
      FILE: '/mypage/club/myclub/MyClubEdit',
      PATH: '/mypage/club/myclub/edit?club=moms',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽아웃도어',
      '4Depth': '가입 현황',
      FILE: '/mypage/club/myclub/MyClubMain',
      PATH: '/mypage/club/myclub?club=outdoor',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '가입',
      FILE: '/mypage/club/myclub/MyClubJoin',
      PATH: '/mypage/club/myclub/join?club=outdoor',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '관심정보 수정',
      FILE: '/mypage/club/myclub/MyClubEdit',
      PATH: '/mypage/club/myclub/edit?club=outdoor',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽펫',
      '4Depth': '가입 현황',
      FILE: '/mypage/club/myclub/MyClubMain',
      PATH: '/mypage/club/myclub?club=pet',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '가입',
      FILE: '/mypage/club/myclub/MyClubJoin',
      PATH: '/mypage/club/myclub/join?club=pet',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '관심정보 수정',
      FILE: '/mypage/club/myclub/MyClubEdit',
      PATH: '/mypage/club/myclub/edit?club=pet',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽헬시',
      '4Depth': '가입 현황',
      FILE: '/mypage/club/myclub/MyClubMain',
      PATH: '/mypage/club/myclub?club=healthy',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '가입',
      FILE: '/mypage/club/myclub/MyClubJoin',
      PATH: '/mypage/club/myclub/join?club=healthy',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '관심정보 수정',
      FILE: '/mypage/club/myclub/MyClubEdit',
      PATH: '/mypage/club/myclub/edit?club=healthy',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽모던',
      '4Depth': '가입 현황',
      FILE: '/mypage/club/myclub/MyClubMain',
      PATH: '/mypage/club/myclub?club=modern',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '가입',
      FILE: '/mypage/club/myclub/MyClubJoin',
      PATH: '/mypage/club/myclub/join?club=modern',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '관심정보 수정',
      FILE: '/mypage/club/myclub/MyClubEdit',
      PATH: '/mypage/club/myclub/edit?club=modern',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽이지웰',
      '4Depth': '가입 현황',
      FILE: '/mypage/club/myclub/MyClubMain',
      PATH: '/mypage/club/myclub?club=ezwel',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽프렌즈',
      '4Depth': '가입 현황',
      FILE: '/mypage/club/myclub/MyClubMain',
      PATH: '/mypage/club/myclub?club=friends',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '쿠폰',
      '3Depth': '보유 쿠폰',
      '4Depth': '',
      FILE: '/mypage/coupon/OwnedCouponList.tsx',
      PATH: '/mypage/coupon/owned',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '2025-07-29',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '사용가능한 쿠폰 없는 경우',
      FILE: '/mypage/coupon/OwnedCouponList.tsx',
      PATH: '/mypage/coupon/owned?status=empty',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 쿠폰 등록하기(D)',
      FILE: '/widgets/coupon/AddCouponDrawer.tsx',
      PATH: '/mypage/coupon/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '다운 가능 쿠폰',
      '4Depth': '',
      FILE: '/mypage/coupon/DownloadableCouponList.tsx',
      PATH: '/mypage/coupon/download',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '사용가능한 쿠폰 없는 경우',
      FILE: '/mypage/coupon/DownloadableCouponList.tsx',
      PATH: '/mypage/coupon/download?status=empty',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '쿠폰 상세(온라인)',
      '4Depth': '쿠폰 적용 대상 (L)',
      FILE: '/widgets/coupon/ApplyCouponTargetDialog.tsx',
      PATH: '/mypage/coupon/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '2025-08-04',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '주차권	[case1. 사용차량번호 미등록한 경우]',
      FILE: '/mypage/coupon/detail/online/parking/ParkingTicketForm.tsx',
      PATH: '/mypage/coupon/detail/parking?status=register',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '주차권 [case2. 차량번호 등록한 경우]',
      FILE: '/mypage/coupon/detail/online/parking/ParkingTicketForm.tsx',
      PATH: '/mypage/coupon/detail/parking?status=use',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '쿠폰 상세(오프라인)',
      '4Depth': '외부 제휴 이벤트',
      FILE: '/mypage/coupon/detail/offline/event/PartnerEventForm.tsx',
      PATH: '	/mypage/coupon/detail/event',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '쿠폰 사용하기',
      FILE: '/widgets/coupon/CouponUseDrawer.tsx',
      PATH: '/mypage/coupon/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 바코드형 (D)',
      FILE: '/widgets/coupon/CouponUseDrawer.tsx',
      PATH: '/mypage/coupon/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 인증키형 (D)',
      FILE: '/widgets/coupon/CouponUseDrawer.tsx',
      PATH: '/mypage/coupon/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 아이체크/직원 확인형 (D)',
      FILE: '/widgets/coupon/CouponUseDrawer.tsx',
      PATH: '/mypage/coupon/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '사용 확인 완료',
      FILE: '/mypage/coupon/detail/offline/complete/UseCompleteForm.tsx',
      PATH: '	/mypage/coupon/detail/complete',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
  ],
} as const;

export default mypage;
