const community = {
  pages: [
    {
      '1Depth': '팝업 모음',
      '2Depth': '항목 추가 (L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/gem/mycollection/add/AddItemDialog',
      PATH: '/gem/etc',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '컬렉션에 상품 추가 (L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/gem/mycollection/add/AddProductDialog',
      PATH: '/gem/etc',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '컬렉션에 브랜드 추가 (L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/gem/mycollection/add/AddBrandDialog',
      PATH: '/gem/etc',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '컬렉션 선택 (L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/gem/mycollection/add/SelectCollectionDrawer',
      PATH: '/gem/etc',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': 'GEM',
      '2Depth': 'PRODUCT',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/gem/gem',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': 'GEM한 상품 없는 경우',
      '4Depth': '',
      FILE: '',
      PATH: '/gem/gem?tab=product&nodata',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'BRAND',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/gem/gem?tab=brand',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': 'GEM한 브랜드 없는 경우',
      '4Depth': '',
      FILE: '',
      PATH: '/gem/gem?tab=brand&nodata',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'COLLECTION',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/gem/gem?tab=collection',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': 'GEM한 컬렉션 없는 경우',
      '4Depth': '',
      FILE: '',
      PATH: '/gem/gem?tab=collection&nodata',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'PEOPLE',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/gem/gem?tab=people',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': 'GEM한 유저 없는 경우',
      '4Depth': '',
      FILE: '',
      PATH: '/gem/gem?tab=people&nodata',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      PATH: '',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': 'MY COLLECTION',
      '2Depth': '목록',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/gem/mycollection/list',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '생성한 컬렉션이 0건일 때 ',
      '4Depth': '',
      FILE: '',
      PATH: '/gem/mycollection/list?nodata',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '상세',
      '3Depth': 'Case 1. 내 컬렉션 상세',
      '4Depth': '',
      FILE: '',
      PATH: '/gem/mycollection/detail?case1',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '비공개',
      FILE: '',
      PATH: '/gem/mycollection/detail?lock',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': 'Case 2. 타인 컬렉션 상세',
      '4Depth': '',
      FILE: '',
      PATH: '/gem/mycollection/detail?case2',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '생성한 컬렉션 내 항목이 0건일 때',
      '4Depth': '',
      FILE: '',
      PATH: '/gem/mycollection/detail?nodata',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '컬렉션명 편집',
      '4Depth': '',
      FILE: '',
      PATH: '/gem/mycollection/detail/edit',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '생성',
      '3Depth': 'Step1. 컬렉션명 입력',
      '4Depth': '',
      FILE: '',
      PATH: '/gem/mycollection/create/name',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': 'Step2. 항목 추가',
      '4Depth': '',
      FILE: '',
      PATH: '/gem/mycollection/create/additems',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '상품과 브랜드 동시에 0건일 때',
      FILE: '',
      PATH: '/gem/mycollection/create/additems?nodata=all',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '상품만 0건일 때',
      FILE: '',
      PATH: '/gem/mycollection/create/additems?nodata=product',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '브랜드만 0건일 때',
      FILE: '',
      PATH: '/gem/mycollection/create/additems?nodata=brand',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': 'Step 3. 컬렉션 공개 설정',
      '4Depth': '',
      FILE: '',
      PATH: '/gem/mycollection/create/visibility',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
  ],
} as const;

export default community;
