const display = {
  pages: [
    // 상품유닛
    {
      '모듈 순위': '공통',
      '모듈 ID': '',
      전시타입: '상품 유닛 - 세로형',
      FILE: '/widgets/display/UnitCase.tsx',
      PATH: '/display?component=vertical',
      작업자: '하윤정',
      상태: 'completed',
      완료일: null,
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': '',
      '모듈 ID': '',
      전시타입: '상품 유닛 - 가로형',
      FILE: '/widgets/display/UnitCase.tsx',
      PATH: '/display?component=horizontal',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '',
      최종수정일: null,
      비고: null,
    },
    /** 1순위 모듈 */
    // 배너 + 이미지 배너
    {
      '모듈 순위': '1순위',
      '모듈 ID': 'HF_BN_LI_01',
      전시타입: '원컬럼 카드형 배너',
      FILE: '/widgets/display/HF_BN_LI_01.tsx',
      PATH: '/display?component=HF_BN_LI_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: '홈피드',
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'HF_BN_IC_01',
      전시타입: '좌/우 스크롤 4.5열 아이콘 배너',
      FILE: '/widgets/display/HF_BN_IC_01.tsx',
      PATH: '/display?component=HF_BN_IC_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: '홈피드',
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'HF_BN_KW_01',
      전시타입: '(홈피드용) 아이콘+키워드 형 좌/우 스크롤 배너',
      FILE: '/widgets/display/HF_BN_KW_01.tsx',
      PATH: '/display?component=HF_BN_KW_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: '홈피드',
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'HF_BN_TX_01',
      전시타입: '가로 1단 말풍선 모듈',
      FILE: '/widgets/display/HF_BN_TX_01.tsx',
      PATH: '/display?component=HF_BN_TX_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: '홈피드',
    },
    {
      '모듈 순위': '',
      '모듈 ID': 'AT_BN_TX_01',
      전시타입: '컬러셋업 띠배너',
      FILE: '/widgets/display/AT_BN_TX_01.tsx',
      PATH: '/display?component=AT_BN_TX_01',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-24',
      최종수정일: null,
      비고: '이머징관',
    },
    {
      '모듈 순위': '',
      '모듈 ID': 'AT_BN_TX_02',
      전시타입: '마퀴 배너',
      FILE: '/widgets/display/AT_BN_TX_02.tsx',
      PATH: '/display?component=AT_BN_TX_02',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-24',
      최종수정일: null,
      비고: '이머징관',
    },
    {
      '모듈 순위': '',
      '모듈 ID': 'CO_BN_CD_01',
      전시타입: '세로 중앙정렬형 전면 메인배너',
      FILE: '/widgets/display/CO_BN_CD_01.tsx',
      PATH: '/display?component=CO_BN_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_CD_02',
      전시타입: '세로 중앙정렬형 전면 메인배너',
      FILE: '/widgets/display/CO_BN_CD_02.tsx',
      PATH: '/display?component=CO_BN_CD_02',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_CD_03',
      전시타입: '1단 가로 리스트 배너',
      FILE: '/widgets/display/CO_BN_CD_03.tsx',
      PATH: '/display?component=CO_BN_CD_03',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_CD_04',
      전시타입: '세로 중앙정렬형 전면 메인배너',
      FILE: '/widgets/display/CO_BN_CD_04.tsx',
      PATH: '/display?component=CO_BN_CD_04',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_CD_05',
      전시타입: '세로 1.5 더보기 배너',
      FILE: '/widgets/display/CO_BN_CD_05.tsx',
      PATH: '/display?component=CO_BN_CD_05',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: '모듈ID변경',
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_CD_06',
      전시타입: '세로 1.5 스와이프 엠블럼 배너',
      FILE: '/widgets/display/CO_BN_CD_06.tsx',
      PATH: '/display?component=CO_BN_CD_06',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_CD_07',
      전시타입: '세로형 스와이프 배너',
      FILE: '/widgets/display/CO_BN_CD_07.tsx',
      PATH: '/display?component=CO_BN_CD_07',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_CD_08',
      전시타입: '1.5열 엠블럼 +  스와이프 배너',
      FILE: '/widgets/display/CO_BN_CD_08.tsx',
      PATH: '/display?component=CO_BN_CD_08',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_CD_09',
      전시타입: '중앙정렬 좌/우 스와이프 3단 배너      ',
      FILE: '/widgets/display/CO_BN_CD_09.tsx',
      PATH: '/display?component=CO_BN_CD_09',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_CD_10',
      전시타입: '1단 가로 리스트 배너',
      FILE: '/widgets/display/CO_BN_CD_10.tsx',
      PATH: '/display?component=CO_BN_CD_10',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_CD_11',
      전시타입: '이미지내 텍스트 노출형 좌/우 스크롤 2.5단 세로 배너',
      FILE: '/widgets/display/CO_BN_CD_11.tsx',
      PATH: '/display?component=CO_BN_CD_11',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_COL2_01',
      전시타입: '정방형 2열 중앙 타이틀 배너',
      FILE: '/widgets/display/CO_BN_COL2_01.tsx',
      PATH: '/display?component=CO_BN_COL2_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_COL2_02',
      전시타입: '정방형 2열 중앙 타이틀 배너',
      FILE: '/widgets/display/CO_BN_COL2_02.tsx',
      PATH: '/display?component=CO_BN_COL2_02',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_IC_01',
      전시타입: '4열 아이콘 배너 아코디언 리스트',
      FILE: '/widgets/display/CO_BN_IC_01.tsx',
      PATH: '/display?component=CO_BN_IC_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_IC_02',
      전시타입: '5열 아이콘 배너 리스트',
      FILE: '/widgets/display/CO_BN_IC_02.tsx',
      PATH: '/display?component=CO_BN_IC_02',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_IC_03',
      전시타입: '4열 아이콘 배너 리스트',
      FILE: '/widgets/display/CO_BN_IC_03.tsx',
      PATH: '/display?component=CO_BN_IC_03',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_IC_04',
      전시타입: '3열 아이콘 배너 리스트',
      FILE: '/widgets/display/CO_BN_IC_04.tsx',
      PATH: '/display?component=CO_BN_IC_04',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_IC_05',
      전시타입: '좌/우 스크롤 4.5열 아이콘 배너',
      FILE: '/widgets/display/CO_BN_IC_05.tsx',
      PATH: '/display?component=CO_BN_IC_05',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_KW_01',
      전시타입: '아이콘+키워드 형 좌/우 스크롤 배너',
      FILE: '/widgets/display/CO_BN_KW_01.tsx',
      PATH: '/display?component=CO_BN_KW_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_LI_01',
      전시타입: '콘텐츠 풀이미지 타이틀 배너',
      FILE: '/widgets/display/CO_BN_LI_01.tsx',
      PATH: '/display?component=CO_BN_LI_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_LI_02',
      전시타입: '가로형 이미지 배너',
      FILE: '/widgets/display/CO_BN_LI_02.tsx',
      PATH: '/display?component=CO_BN_LI_02',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_LI_03',
      전시타입: '수기등록 이미지 배너',
      FILE: '/widgets/display/CO_BN_LI_03.tsx',
      PATH: '/display?component=CO_BN_LI_03',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_LI_04',
      전시타입: '1열 슬림 이미지 타이틀 배너',
      FILE: '/widgets/display/CO_BN_LI_04.tsx',
      PATH: '/display?component=CO_BN_LI_04',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_LI_05',
      전시타입: '슬림 이미지 타이틀 배너',
      FILE: '/widgets/display/CO_BN_LI_05.tsx',
      PATH: '/display?component=CO_BN_LI_05',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_LI_06',
      전시타입: '콘텐츠 아코디언 모듈',
      FILE: '/widgets/display/CO_BN_LI_06.tsx',
      PATH: '/display?component=CO_BN_LI_06',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_LI_07',
      전시타입: '1단 띠 배너 롤링 타입',
      FILE: '/widgets/display/CO_BN_LI_07.tsx',
      PATH: '/display?component=CO_BN_LI_07',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_SIV_01',
      전시타입: '플리킹 이미지+ 영상 배너',
      FILE: '/widgets/display/CO_BN_SIV_01.tsx',
      PATH: '/display?component=CO_BN_SIV_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_TX_01',
      전시타입: '버튼형 배너',
      FILE: '/widgets/display/CO_BN_TX_01.tsx',
      PATH: '/display?component=CO_BN_TX_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_IF_TX_01',
      전시타입: '안내사항 텍스트',
      FILE: '/widgets/display/CO_IF_TX_01.tsx',
      PATH: '/display?component=CO_IF_TX_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_IF_TX_02',
      전시타입: '텍스트 영역 모듈',
      FILE: '/widgets/display/CO_IF_TX_02.tsx',
      PATH: '/display?component=CO_IF_TX_02',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_LI_08',
      전시타입: '구매혜택 (배너형)',
      FILE: '/widgets/display/CO_BN_LI_08.tsx',
      PATH: '/display?component=CO_BN_LI_08',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'LV_BN_LI_01',
      전시타입: '구매혜택 (상품-직접등록형)',
      FILE: '/widgets/display/LV_BN_LI_01.tsx',
      PATH: '/display?component=LV_BN_LI_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'LV_TB_LI_01',
      전시타입: '라이브 캘린더 모듈',
      FILE: '/widgets/display/LV_TB_LI_01.tsx',
      PATH: '/display?component=LV_TB_LI_01',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-08-22',
      최종수정일: null,
      비고: '모듈 제외',
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'HF_PD_COL2_01',
      전시타입: '2단 2열 상품',
      FILE: '/widgets/display/HF_PD_COL2_01.tsx',
      PATH: '/display?component=HF_PD_COL2_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-26',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'AU_PD_CD_01',
      전시타입: '옥션 상품',
      FILE: '/widgets/display/AU_PD_CD_01.tsx',
      PATH: '/display?component=AU_PD_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-26',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'DE_PD_CD_01',
      전시타입: '타임딜 사각형 상품',
      FILE: '/widgets/display/DE_PD_CD_01.tsx',
      PATH: '/display?component=DE_PD_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-26',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_PD_GD_01',
      전시타입: '2단 2.5열 상품',
      FILE: '/widgets/display/CO_PD_GD_01.tsx',
      PATH: '/display?component=CO_PD_GD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-26',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_PD_COL2_01',
      전시타입: '2단 2열 상품',
      FILE: '/widgets/display/CO_PD_COL2_01.tsx',
      PATH: '/display?component=CO_PD_COL2_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-26',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'SB_PD_CD_01',
      전시타입: '1.5열 스와이프 구독상품',
      FILE: '/widgets/display/SB_PD_CD_01.tsx',
      PATH: '/display?component=SB_PD_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-26',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_PD_MS_01',
      전시타입: '액자형 상품 모듈',
      FILE: '/widgets/display/CO_PD_MS_01.tsx',
      PATH: '/display?component=CO_PD_MS_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-26',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'PR_PD_CD_01',
      전시타입: '선공개 상품 리스트',
      FILE: '/widgets/display/PR_PD_CD_01.tsx',
      PATH: '/display?component=PR_PD_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-27',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'RF_PD_CD_01',
      전시타입: '1열 스와이프 래플 상품',
      FILE: '/widgets/display/RF_PD_CD_01.tsx',
      PATH: '/display?component=RF_PD_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-26',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'RF_PD_CD_02',
      전시타입: '리스트형 세로 래플 상품',
      FILE: '/widgets/display/RF_PD_CD_02.tsx',
      PATH: '/display?component=RF_PD_CD_02',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-26',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'RV_PD_CD_01',
      전시타입: '좌우스와이프 리뷰 상품',
      FILE: '/widgets/display/RV_PD_CD_01.tsx',
      PATH: '/display?component=RV_PD_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-26',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'TM_PD_COL2_01',
      전시타입: '2열 타임세일 상품',
      FILE: '/widgets/display/TM_PD_COL2_01.tsx',
      PATH: '/display?component=TM_PD_COL2_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-26',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'TM_PD_CD_01',
      전시타입: '1.5열 타임세일 상품',
      FILE: '/widgets/display/TM_PD_CD_01.tsx',
      PATH: '/display?component=TM_PD_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-26',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_PD_COL2_02',
      전시타입: '2단 2.5열 더보기 상품모듈',
      FILE: '/widgets/display/CO_PD_COL2_02.tsx',
      PATH: '/display?component=CO_PD_COL2_02',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-27',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_PD_COL2_03',
      전시타입: '2단 2.5열 카테고리 상품 리스트',
      FILE: '/widgets/display/CO_PD_COL2_03.tsx',
      PATH: '/display?component=CO_PD_COL2_03',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_TP_CD_01',
      전시타입: '탭 상품 리스트',
      FILE: '/widgets/display/CO_TP_CD_01.tsx',
      PATH: '/display?component=CO_TP_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-28',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_TP_CD_02',
      전시타입: '3열 사각 탭 상품 모듈',
      FILE: '/widgets/display/CO_TP_CD_02.tsx',
      PATH: '/display?component=CO_TP_CD_02',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-28',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_TP_CD_03',
      전시타입: '2열 사각 탭 상품 모듈',
      FILE: '/widgets/display/CO_TP_CD_03.tsx',
      PATH: '/display?component=CO_TP_CD_03',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-28',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_TP_COL2_01',
      전시타입: '2단 탭 2열 상품 리스트 모듈',
      FILE: '/widgets/display/CO_TP_COL2_01.tsx',
      PATH: '/display?component=CO_TP_COL2_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-28',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'BT_TP_LI_01',
      전시타입: '바우처 리스트 모듈',
      FILE: '/widgets/display/BT_TP_LI_01.tsx',
      PATH: '/display?component=BT_TP_LI_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-28',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'HF_BP_COL2_01',
      전시타입: '배너1+상품 2열 리스트',
      FILE: '/widgets/display/HF_BP_COL2_01.tsx',
      PATH: '/display?component=HF_BP_COL2_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-28',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BP_CD_01',
      전시타입: '배너 + 2.5 가로 스크롤 상품',
      FILE: '/widgets/display/CO_BP_CD_01.tsx',
      PATH: '/display?component=CO_BP_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-28',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BP_LI_01',
      전시타입: '가로배너+가로 더보기 상품',
      FILE: '/widgets/display/CO_BP_LI_01.tsx',
      PATH: '/display?component=CO_BP_LI_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-28',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BP_LI_02',
      전시타입: '세로배너+1.5 가로 스와이프 상품',
      FILE: '/widgets/display/CO_BP_LI_02.tsx',
      PATH: '/display?component=CO_BP_LI_02',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-28',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BP_LI_03',
      전시타입: '본문형 가로배너',
      FILE: '/widgets/display/CO_BP_LI_03.tsx',
      PATH: '/display?component=CO_BP_LI_03',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-28',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BP_CD_02',
      전시타입: '원형 배너 상픔 2.5 스와이프 리스트',
      FILE: '/widgets/display/CO_BP_CD_02.tsx',
      PATH: '/display?component=CO_BP_CD_02',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-28',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_TB_GD_01',
      전시타입: '탭 세로배너 3열 상품',
      FILE: '/widgets/display/CO_TB_GD_01.tsx',
      PATH: '/display?component=CO_TB_GD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-27',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_TB_GD_02',
      전시타입: '탭 세로배너 3열 상품+한번에 담기+더보기',
      FILE: '/widgets/display/CO_TB_GD_02.tsx',
      PATH: '/display?component=CO_TB_GD_02',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-27',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_TB_GD_03',
      전시타입: '구획형 탭 이미지 상품모듈',
      FILE: '/widgets/display/CO_TB_GD_03.tsx',
      PATH: '/display?component=CO_TB_GD_03',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-27',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'SF_TV_CD_01',
      전시타입: '2.5열 탭 숏폼',
      FILE: '/widgets/display/SF_TV_CD_01.tsx',
      PATH: '/display?component=SF_TV_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'SF_VD_LI_01',
      전시타입: '1열 전체 숏폼',
      FILE: '/widgets/display/SF_VD_LI_01.tsx',
      PATH: '/display?component=SF_VD_LI_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'SF_VD_CD_01',
      전시타입: '1.5열 가로스크롤 숏폼',
      FILE: '/widgets/display/SF_VD_CD_01.tsx',
      PATH: '/display?component=SF_VD_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'HF_VD_COL2_01',
      전시타입: '홈피드용 2열 숏폼 리스트',
      FILE: '/widgets/display/HF_VD_COL2_01.tsx',
      PATH: '/display?component=HF_VD_COL2_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_SP_01',
      전시타입: '스페이싱 모듈',
      FILE: '/widgets/display/CO_SP_01.tsx',
      PATH: '/display?component=CO_SP_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'BR_BN_CD_01',
      전시타입: '브랜드프로필 모듈',
      FILE: '/widgets/display/BR_BN_CD_01.tsx',
      PATH: '/display?component=BR_BN_CD_01',
      작업자: '최수연',
      상태: 'waiting',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: '기획 검토 중',
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'BR_BN_CD_02',
      전시타입: '셀러 목록 모듈',
      FILE: '/widgets/display/BR_BN_CD_02.tsx',
      PATH: '/display?component=BR_BN_CD_02',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BP_LI_04',
      전시타입: '1열 셀러 프로필 모듈',
      FILE: '/widgets/display/CO_BP_LI_04.tsx',
      PATH: '/display?component=CO_BP_LI_04',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_TB_CD_01',
      전시타입: '1열 탭형 배너',
      FILE: '/widgets/display/CO_TB_CD_01.tsx',
      PATH: '/display?component=CO_TB_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_TB_COL2_01',
      전시타입: '탭+정방형 2열 중앙 타이틀 배너',
      FILE: '/widgets/display/CO_TB_COL2_01.tsx',
      PATH: '/display?component=CO_TB_COL2_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_TB_COL2_02',
      전시타입: '탭+정방형 2열 외부 타이틀 배너',
      FILE: '/widgets/display/CO_TB_COL2_02.tsx',
      PATH: '/display?component=CO_TB_COL2_02',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'RK_PD_CD_01',
      전시타입: '전문관 베스트 상품 리스트',
      FILE: '/widgets/display/RK_PD_CD_01.tsx',
      PATH: '/display?component=RK_PD_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: '모듈ID변경',
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'BR_RK_CD_01',
      전시타입: '세로2.5열 스크롤 베스트',
      FILE: '/widgets/display/BR_RK_CD_01.tsx',
      PATH: '/display?component=BR_RK_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'LV_TB_LI_01',
      전시타입: '라이브 캘린더 모듈',
      FILE: '/widgets/display/LV_TB_LI_01.tsx',
      PATH: '/display?component=LV_TB_LI_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'LV_VD_CD_01',
      전시타입: '최신 라이브 자동 리스트',
      FILE: '/widgets/display/LV_VD_CD_01.tsx',
      PATH: '/display?component=LV_VD_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BTP_CD_01',
      전시타입: '배너 탭 2.5 스와이프 상품',
      FILE: '/widgets/display/CO_BTP_CD_01.tsx',
      PATH: '/display?component=CO_BTP_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-29',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'LV_BN_CD_01',
      전시타입: '라이브 알림신청 배너(수동)',
      FILE: '/widgets/display/LV_BN_CD_01.tsx',
      PATH: '/display?component=LV_BN_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-05',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'LV_BN_CD_02',
      전시타입: '라이브 알림신청 배너(자동)',
      FILE: '/widgets/display/LV_BN_CD_02.tsx',
      PATH: '/display?component=LV_BN_CD_02',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-05',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': '2순위',
      '모듈 ID': 'MS_BN_CD_01',
      전시타입: '1열 미스페이스 모듈',
      FILE: '/widgets/display/MS_BN_CD_01.tsx',
      PATH: '/display?component=MS_BN_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-05',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'MS_BN_COL2_01',
      전시타입: '2열 미스페이스 모듈',
      FILE: '/widgets/display/MS_BN_COL2_01.tsx',
      PATH: '/display?component=MS_BN_COL2_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-05',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'BR_UP_CD_01',
      전시타입: '1.5열 미스페이스 프로필 모듈',
      FILE: '/widgets/display/BR_UP_CD_01.tsx',
      PATH: '/display?component=BR_UP_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-05',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CA_MS_CD_01',
      전시타입: '1열 미스페이스 모듈(Top10)',
      FILE: '/widgets/display/CA_MS_CD_01.tsx',
      PATH: '/display?component=CA_MS_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-05',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'BR_MS_CD_01',
      전시타입: '1.5열 미스페이스 모듈',
      FILE: '/widgets/display/BR_MS_CD_01.tsx',
      PATH: '/display?component=BR_MS_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-05',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'Contents_timer_01',
      전시타입: '기획전 남은시간',
      FILE: '/widgets/display/Contents_timer_01.tsx',
      PATH: '/display?component=Contents_timer_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-05',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'HF_UP_CD_01',
      전시타입: '1.5열 미스페이스 프로필',
      FILE: '/widgets/display/HF_UP_CD_01.tsx',
      PATH: '/display?component=HF_UP_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-05',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'MS_UP_CD_01',
      전시타입: '1.5열 미스페이스 프로필 모듈',
      FILE: '/widgets/display/MS_UP_CD_01.tsx',
      PATH: '/display?component=MS_UP_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-05',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'HF_MS_LI_01',
      전시타입: '(홈피드용) 1열 미스페이스 콘텐츠',
      FILE: '/widgets/display/HF_MS_LI_01.tsx',
      PATH: '/display?component=HF_MS_LI_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-05',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'MS_BP_CD_01',
      전시타입: '1.5열 미스페이스 상품 썸네일 리스트',
      FILE: '/widgets/display/MS_BP_CD_01.tsx',
      PATH: '/display?component=MS_BP_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-05',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CA_BN_CD_01',
      전시타입: '1.5열 콘텐츠 리스트 배너(매거진)',
      FILE: '/widgets/display/CA_BN_CD_01.tsx',
      PATH: '/display?component=CA_BN_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-05',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'HF_RC_GD_01',
      전시타입: '혼합 추천 모듈',
      FILE: '/widgets/display/HF_RC_GD_01.tsx',
      PATH: '/display?component=HF_RC_GD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-05',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_BN_LI_10',
      전시타입: '전면 기획전 이미지 배너',
      FILE: '/widgets/display/CO_BN_LI_10.tsx',
      PATH: '/display?component=CO_BN_LI_10',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-05',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'BR_BN_CD_06',
      전시타입: '브랜드룩북 배너',
      FILE: '/widgets/display/BR_BN_CD_06.tsx',
      PATH: '/display?component=BR_BN_CD_06',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-05',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'BR_BN_CD_07',
      전시타입: '가로형 1단 롤링 배너',
      FILE: '/widgets/display/BR_BN_CD_07.tsx',
      PATH: '/display?component=BR_BN_CD_07',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-05',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'BR_BN_CD_08',
      전시타입: '중앙정렬 좌/우 스와이프 3단 배너',
      FILE: '/widgets/display/BR_BN_CD_08.tsx',
      PATH: '/display?component=BR_BN_CD_08',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-05',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': '3순위',
      '모듈 ID': 'CO_TG_GD_02',
      전시타입: '좌표 배너 축소 리스트',
      FILE: '/widgets/display/CO_TG_GD_02.tsx',
      PATH: '/display?component=CO_TG_GD_02',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-18',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_TG_GD_01',
      전시타입: '좌표+상품 더보기 배너',
      FILE: '/widgets/display/CO_TG_GD_01.tsx',
      PATH: '/display?component=CO_TG_GD_01',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-18',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'HF_BN_CD_01',
      전시타입: '1컬럼 가로형 상단용 피드형 배너',
      FILE: '/widgets/display/HF_BN_CD_01.tsx',
      PATH: '/display?component=HF_BN_CD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-19',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'HF_BN_CD_04',
      전시타입: '홈피드 2열 세로 배너',
      FILE: '/widgets/display/HF_BN_CD_04.tsx',
      PATH: '/display?component=HF_BN_CD_04',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-19',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'HF_BN_TX_02',
      전시타입: '가로형 1단 챗봇 모듈',
      FILE: '/widgets/display/HF_BN_TX_02.tsx',
      PATH: '/display?component=HF_BN_TX_02',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-19',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'HF_TIMER_01',
      전시타입: '1열 가로형 타이머 모듈_수기등록 시',
      FILE: '/widgets/display/HF_TIMER_01.tsx',
      PATH: '/display?component=HF_TIMER_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-19',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'HF_PR_LI_01',
      전시타입: '1열 가로형 타이머 모듈_선공개상품 ID맵핑 시',
      FILE: '/widgets/display/HF_PR_LI_01.tsx',
      PATH: '/display?component=HF_PR_LI_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-19',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'HF_CL_COL2_01',
      전시타입: '2열 세로형 컬렉션',
      FILE: '/widgets/display/HF_CL_COL2_01.tsx',
      PATH: '/display?component=HF_CL_COL2_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-19',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'HF_LV_GD_01',
      전시타입: '1열 영상 + 상품 + 아이콘',
      FILE: '/widgets/display/HF_LV_GD_01.tsx',
      PATH: '/display?component=HF_LV_GD_01',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-19',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'CO_TP_LI_11',
      전시타입: '2열 탭+가격필터 상품',
      FILE: '/widgets/display/CO_TP_LI_11.tsx',
      PATH: '/display?component=CO_TP_LI_11',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-09-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'RK_TP_LI_01',
      전시타입: '2열 탭+가격필터 랭킹 상품',
      FILE: '/widgets/display/RK_TP_LI_01.tsx',
      PATH: '/display?component=RK_TP_LI_01',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-09-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'AT_TB_LI_01',
      전시타입: '탭 + 텍스트 배너',
      FILE: '/widgets/display/AT_TB_LI_01.tsx',
      PATH: '/display?component=AT_TB_LI_01',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-24',
      최종수정일: null,
      비고: '',
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'BT_PD_CD_01',
      전시타입: '2.5열 N+N 상품 리스트',
      FILE: '/widgets/display/BT_PD_CD_01.tsx',
      PATH: '/display?component=BT_PD_CD_01',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-25',
      최종수정일: null,
      비고: '',
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'FD_SALE_01',
      전시타입: '식품전문관 SALE 상품리스트',
      FILE: '/widgets/display/FD_SALE_01.tsx',
      PATH: '/display?component=FD_SALE_01',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-25',
      최종수정일: null,
      비고: '',
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'FD_TM_PD_01',
      전시타입: '마감세일 상품 2.5 리스트',
      FILE: '/widgets/display/FD_TM_PD_01.tsx',
      PATH: '/display?component=FD_TM_PD_01',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-25',
      최종수정일: null,
      비고: '',
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'MS_BN_CD_02',
      전시타입: '1열 미스페이스+가로 상품 리스트',
      FILE: '/widgets/display/MS_BN_CD_02.tsx',
      PATH: '/display?component=MS_BN_CD_02',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-25',
      최종수정일: null,
      비고: '',
    },
    {
      '모듈 순위': null,
      '모듈 ID': 'rsvp_rcmm_01',
      전시타입: 'RSVP_개인화',
      FILE: '/widgets/display/Rsvp_rcmm_01.tsx',
      PATH: '/display?component=Rsvp_rcmm_01',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-29',
      최종수정일: null,
      비고: '',
    },
  ],
} as const;

export default display;
