const shop = {
  pages: [
    // 전문관
    {
      '1Depth': '전문관',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '/store/Store.tsx',
      PATH: '/store',
      작업자: '최수연',
      상태: 'progress',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '베스트',
      '3Depth': '',
      '4Depth': '',
      FILE: '/store/StoreBest.tsx',
      PATH: '/store',
      작업자: '최수연',
      상태: 'progress',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '브랜드',
      '3Depth': '',
      '4Depth': '',
      FILE: '/store/StoreBrand.tsx',
      PATH: '/store',
      작업자: '최수연',
      상태: 'progress',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '신상',
      '3Depth': '',
      '4Depth': '',
      FILE: '/store/StoreNew.tsx',
      PATH: '/store',
      작업자: '최수연',
      상태: 'progress',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    // 홈피드
    {
      '1Depth': '홈피드',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '/homefeed/HomeFeed.tsx',
      PATH: '/homefeed',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-22',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '라이브 토스트',
      '3Depth': '',
      '4Depth': '',
      FILE: '/homefeed/LiveToast.tsx',
      PATH: '/homefeed',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-09-22',
      최종수정일: '',
      비고: '',
    },
    // 카테고리
    {
      '1Depth': '카테고리',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '/category/CategoryMenu.tsx',
      PATH: '/category',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-07-21',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '대카테고리',
      '3Depth': '',
      '4Depth': '',
      FILE: '/category/CategoryDepth1.tsx',
      PATH: '/category/depth1',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-07-21',
      최종수정일: '',
      비고: '필터영역 TBD',
    },
    {
      '1Depth': '',
      '2Depth': '중소카테고리',
      '3Depth': '',
      '4Depth': '',
      FILE: '/category/CategoryDepth2.tsx',
      PATH: '/category/depth2',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-07-21',
      최종수정일: '',
      비고: '필터영역 TBD',
    },
    // 샵메인
    {
      '1Depth': '샵메인',
      '2Depth': 'SHOP(T)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/main/ShopMain.tsx',
      PATH: '/shop/main',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-07-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '쇼룸 모아보기',
      '4Depth': '',
      FILE: '/shop/showroom/Showroom.tsx',
      PATH: '/shop/showroom',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-07-08',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'BRAND(T)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/main/BrandMain.tsx',
      PATH: '/shop/brand',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-08-19',
      최종수정일: '',
      비고: '전시모듈 제외',
    },
    // 브랜드관
    {
      '1Depth': '브랜드관',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '/brand/BrandStore.tsx',
      PATH: '/brand',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-08-19',
      최종수정일: '',
      비고: '전시모듈 제외',
    },
    {
      '1Depth': '',
      '2Depth': 'Style1',
      '3Depth': '',
      '4Depth': '',
      FILE: '/brand/BrandStore.tsx',
      PATH: '/brand?variant=style1',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-08-19',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'Style2',
      '3Depth': '',
      '4Depth': '',
      FILE: '/brand/BrandStore.tsx',
      PATH: '/brand?variant=style2',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-08-19',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '상품 목록 (full case)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/brand/BrandShop.tsx',
      PATH: '/brand/shop',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-08-19',
      최종수정일: '',
      비고: '',
    },
    // 콘텐츠
    {
      '1Depth': '콘텐츠',
      '2Depth': '모아보기',
      '3Depth': '',
      '4Depth': '',
      FILE: '/contents/ContOverview.tsx',
      PATH: '/contents/overview',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-08-25',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 에디토리얼(T)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/contents/overview/ContEditorial.tsx',
      PATH: '/contents/overview?tab=editorial',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-08-25',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 룩북(T)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/contents/overview/ContLookbook.tsx',
      PATH: '/contents/overview?tab=lookbook',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-08-25',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 숏폼(T)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/contents/overview/ContShortform.tsx',
      PATH: '/contents/overview?tab=shortform',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-08-25',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 미스페이스(T)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/contents/overview/ContMespace.tsx',
      PATH: '/contents/overview?tab=mespace',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-08-25',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 컬렉션(T)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/contents/overview/ContCollection.tsx',
      PATH: '/contents/overview?tab=collection',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-08-25',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '상세',
      '3Depth': '',
      '4Depth': '',
      FILE: '/contents/ContDetail.tsx',
      PATH: '/contents/detail',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-08-25',
      최종수정일: '',
      비고: '',
    },
    // 서비스매장
    {
      '1Depth': '서비스매장',
      '2Depth': '도착보장관',
      '3Depth': '',
      '4Depth': '',
      FILE: '/servicestore/ServiceStoreGuaranteeOverview.tsx',
      PATH: '/servicestore/guarantee',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-09-24',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '서브',
      '4Depth': '',
      FILE: '/servicestore/ServiceStoreGuaranteeSub.tsx',
      PATH: '/servicestore/guarantee/sub',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-09-24',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '선물하기관',
      '3Depth': '',
      '4Depth': '',
      FILE: '/servicestore/ServiceStoreGiftOverview.tsx',
      PATH: '/servicestore/gift',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-09-24',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '서브',
      '4Depth': '',
      FILE: '/servicestore/ServiceStoreGiftSub.tsx',
      PATH: '/servicestore/gift/sub',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-09-24',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '구독관',
      '3Depth': '',
      '4Depth': '',
      FILE: '/servicestore/ServiceStoreSubscriptionOverview.tsx',
      PATH: '/servicestore/subscription',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-09-24',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '여행관',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '김효정',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '팝업관',
      '3Depth': '',
      '4Depth': '',
      FILE: '/servicestore/ServiceStorePopupOverview.tsx',
      PATH: '/servicestore/popup',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-09-24',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '라이브관',
      '3Depth': '',
      '4Depth': '',
      FILE: '/servicestore/ServiceStoreLiveOverview.tsx',
      PATH: '/servicestore/live',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-09-24',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '디지털가이드북',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '정지우',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '라이브 미리보기',
      '3Depth': '',
      '4Depth': '',
      FILE: '/servicestore/ServiceStoreLiveDetail.tsx',
      PATH: '/servicestore/preview',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-08-25',
      최종수정일: '',
      비고: '',
    },
    // 컨셉스토어
    {
      '1Depth': '컨셉스토어',
      '2Depth': 'Attag관',
      '3Depth': '',
      '4Depth': '',
      FILE: '/concept/ConceptAttag.tsx',
      PATH: '/concept/attag',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-24',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '상품',
      '4Depth': '',
      FILE: '/concept/ConceptAttagProducts.tsx',
      PATH: '/concept/attag/list',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-24',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '식품관',
      '3Depth': '',
      '4Depth': '',
      FILE: '/concept/ConceptFood.tsx',
      PATH: '/concept/food',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-25',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '서브',
      '4Depth': '셰프의 테이블',
      FILE: '/concept/ConceptFoodSub.tsx',
      PATH: '/concept/food/sub?page=chef',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '위대한 생산자',
      FILE: '/concept/ConceptFoodSub.tsx',
      PATH: '/concept/food/sub?page=producer',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '세계의 장인',
      FILE: '/concept/ConceptFoodSub.tsx',
      PATH: '/concept/food/sub?page=artisan',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '미식가의 도구상점',
      FILE: '/concept/ConceptFoodSub.tsx',
      PATH: '/concept/food/sub?page=tools',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'RSVP',
      '3Depth': '',
      '4Depth': '',
      FILE: '/concept/ConceptRsvp.tsx',
      PATH: '/concept/rsvp',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 브랜드 (T)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/concept/ConceptRsvp.tsx',
      PATH: '/concept/rsvp?tab=brand',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 추천브랜드 키워드X',
      '3Depth': '',
      '4Depth': '',
      FILE: '/concept/ConceptRsvp.tsx',
      PATH: '/concept/rsvp?tab=brand&nodata',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 관심카테고리 설정X',
      '3Depth': '',
      '4Depth': '',
      FILE: '/concept/ConceptRsvp.tsx',
      PATH: '/concept/rsvp?tab=brand&nokeyword',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '상품',
      '4Depth': '',
      FILE: '/concept/ConceptRsvpProducts.tsx',
      PATH: '/concept/rsvp/list',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '서브',
      FILE: '/concept/ConceptRsvpProductsSub.tsx',
      PATH: '/concept/rsvp/list/sub',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '2025-09-29',
      최종수정일: '',
      비고: '',
    },

    // * 상품 상세 - 일반
    {
      '1Depth': '상품 상세',
      '2Depth': '공통',
      '3Depth': '판매중',
      '4Depth': '',
      FILE: '/shop/detail/DetailAll.tsx',
      PATH: '/shop/detail',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '진입 시 설정 팝업',
      '4Depth': '이미지, 타이틀 X',
      FILE: '/shop/detail/DetailOpenDialog.tsx',
      PATH: '/shop/detail/etc',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-08',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '비디오, 타이틀 O',
      FILE: '/shop/detail/DetailOpenDialog.tsx',
      PATH: '/shop/detail/etc?video',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-08',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '여러개 CASE',
      FILE: '/shop/detail/DetailOpenDialog.tsx',
      PATH: '/shop/detail/etc',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-19',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '에러',
      '4Depth': '일시정지',
      FILE: '/shop/detail/ErrorDetail.tsx',
      PATH: '/shop/detail/preparing',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '접근불가',
      FILE: '/shop/detail/ErrorDetail.tsx',
      PATH: '/shop/detail/error',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '성인인증',
      '4Depth': '',
      FILE: '/shop/detail/AgeCheckDetail.tsx',
      PATH: '/shop/detail/age',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 스페셜브랜드',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/detail/DetailAll.tsx',
      PATH: '/shop/detail?specialBrand',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '상세 상단',
      '2Depth': '스페셜브랜드 로고 영역',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/brand/BrandHeader.tsx',
      PATH: '/shop/detail/pub?comp=specialbrand',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '썸네일 영역',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/top/DetailTopSlide.tsx',
      PATH: '/shop/detail/pub?comp=thumbnail',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '브랜드명 바 영역',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/top/DetailTopBar.tsx',
      PATH: '/shop/detail/pub?comp=topbar',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 바코드조회(L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/top/BarcodeDialog.tsx',
      PATH: '/shop/detail/etc',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '상품명 영역',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/top/DetailTop.tsx',
      PATH: '/shop/detail/pub?comp=title',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 품절 텍스트',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/top/DetailTop.tsx',
      PATH: '/shop/detail/pub?comp=title&soldout',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '가격 영역',
      '3Depth': '일반',
      '4Depth': '',
      FILE: '/widgets/detail/top/DetailPrice.tsx',
      PATH: '/shop/detail/pub?comp=price',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '2025-09-03',
      비고: '문화센터,렌탈',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '옥션',
      '4Depth': '',
      FILE: '/widgets/detail/top/DetailPriceAuction.ts',
      PATH: '/shop/detail/pub?comp=auctionprice',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '래플',
      '4Depth': '',
      FILE: '/widgets/detail/top/DetailPriceRaffle.tsx',
      PATH: '/shop/detail/pub?comp=raffleprice',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '딜',
      '4Depth': '',
      FILE: '/widgets/detail/top/DetailPriceDeal.tsx',
      PATH: '/shop/detail/pub?comp=price',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },

    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '세일 정보 O',
      '4Depth': '세일',
      FILE: '/widgets/detail/top/DetailPrice.tsx',
      PATH: '/shop/detail/pub?comp=price&sale',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '타임세일',
      FILE: '/widgets/detail/top/DetailPrice.tsx',
      PATH: '/shop/detail/pub?comp=price&sale&time',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '가격문의',
      '4Depth': '',
      FILE: '/widgets/detail/top/DetailPrice.tsx',
      PATH: '/shop/detail/pub?comp=price',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 쿠폰 전체 받기(L)',
      '4Depth': '',
      FILE: '/widgets/coupon/CouponDialog.tsx',
      PATH: '/shop/detail/etc',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },

    {
      '1Depth': '',
      '2Depth': '상단 추가정보 영역',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/top/DetailTopAddInfo.tsx',
      PATH: '/shop/detail/pub?comp=addinfo',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },

    {
      '1Depth': '상세 중간',
      '2Depth': '최대 혜택가 (혜택 계산기)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/middle/BenefitCalc.tsx',
      PATH: '/shop/detail/pub?comp=calc',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },

    {
      '1Depth': '',
      '2Depth': '교차할인',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/middle/CrossDiscount.ts',
      PATH: '/shop/detail/pub?comp=crossdiscount',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 함께 구매 가능한 상품 보기(L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/middle/CrossDiscountDialog.tsx',
      PATH: '/shop/detail/etc',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },

    {
      '1Depth': '',
      '2Depth': '추가혜택',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/middle/DetailBenefit.tsx',
      PATH: '/shop/detail/pub?comp=benefits',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },

    {
      '1Depth': '',
      '2Depth': '배송안내',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/middle/DetailDelivery.tsx',
      PATH: '/shop/detail/pub?comp=delivery',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },

    {
      '1Depth': '',
      '2Depth': '다른 지점 동일 상품',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/middle/SameProdBranch.tsx',
      PATH: '/shop/detail/pub?comp=sameprodbranch',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 지점 별 재고 현황(L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/middle/SameProdBranchDialog.tsx',
      PATH: '/shop/detail/etc',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },

    {
      '1Depth': '',
      '2Depth': '사은품+포장 안내',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/middle/GiftPackageInfo.tsx',
      PATH: '/shop/detail/pub?comp=giftpackage',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 대상 상품 모두보기(L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/middle/GiftTargetProductDialog.tsx',
      PATH: '/shop/detail/etc',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },

    {
      '1Depth': '',
      '2Depth': '브랜드 배너+공지',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/bottom/DetailBrand.tsx',
      PATH: '/shop/detail/pub?comp=brand',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '이벤트, 프로모션 배너',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/middle/DetailBanner.tsx',
      PATH: '/shop/detail/pub?comp=banner',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },

    {
      '1Depth': '',
      '2Depth': '탭 노출 CASE',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/detail/DetailAll.tsx',
      PATH: '/shop/detail/pub?comp=prodtab',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '상단 공지 영역',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/desc/ProdNotice.tsx',
      PATH: '/shop/detail/pub?comp=prodnotice',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '상세 영역',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/desc/ProdDesc.tsx',
      PATH: '/shop/detail/pub?comp=proddesc',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '2025-09-22',
      비고: '여행',
    },
    {
      '1Depth': '',
      '2Depth': '	⤷ 위약금 고정 case',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/desc/ProdDesc.tsx',
      PATH: '/shop/detail/pub?comp=proddesc&penalty',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '여행 아이콘',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/desc/TripIcons.tsx',
      PATH: '/shop/detail/pub?comp=tripicons',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-22',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '상품정보고시',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/desc/EssentialInfo.tsx',
      PATH: '/shop/detail/pub?comp=essentialinfo',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '2025-09-03',
      비고: '문화센터,렌탈',
    },
    {
      '1Depth': '',
      '2Depth': '연관 상품',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/desc/RelatedProd.tsx',
      PATH: '/shop/detail/pub?comp=relatedprod',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '리뷰',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/DetailReview.tsx',
      PATH: '/shop/detail/pub?comp=review',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '2025-09-25',
      비고: '딜상품 포토리뷰 미노출',
    },
    {
      '1Depth': '',
      '2Depth': '전체보기',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/review/Review.tsx',
      PATH: '/shop/review/all',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '신고하기(L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/review/ReviewReportDialog.tsx',
      PATH: '/shop/review/all',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '2025-09-25',
      비고: '팝업으로 수정',
    },
    {
      '1Depth': 'Q&A',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/DetailQnA.tsx',
      PATH: '/shop/detail/pub?comp=qna',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '전체보기',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/qna/QnA.tsx',
      PATH: '/shop/qna',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '딜상품',
      '4Depth': '',
      FILE: '/shop/qna/QnA.tsx',
      PATH: '/shop/qna?deal',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '미스페이스, 숏폼, 관련콘텐츠',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/bottom/BottomBanners.tsx',
      PATH: '/shop/detail/pub?comp=bottombanners',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },

    {
      '1Depth': '상세 하단',
      '2Depth': 'CTA 영역',
      '3Depth': '전체 CASE',
      '4Depth': '',
      FILE: '/widgets/detail/cta/DetailCTA.tsx',
      PATH: '/shop/detail/pub?comp=cta',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '2025-09-25',
      비고: '예약구매 팝업 관련 수정',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '일반 CTA',
      '4Depth': '',
      FILE: '/widgets/detail/cta/GeneralCTA.tsx',
      PATH: '/shop/detail/pub?comp=cta',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '2025-09-23',
      비고: '여행',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 날짜 선택 영역(L)',
      '4Depth': '시간 선택',
      FILE: '/widgets/detail/cta/drawer/SelectDateSection.tsx',
      PATH: '/shop/detail/etc',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '2025-09-23',
      비고: '여행',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '시간 상시',
      FILE: '/widgets/detail/cta/SelectDateDialog.tsx',
      PATH: '/shop/detail/etc?always',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '2025-09-23',
      비고: '여행',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 예약 구매 안내(L)',
      '4Depth': '',
      FILE: '/widgets/detail/cta/ReserveDialog.tsx',
      PATH: '/shop/detail/etc',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '상태 CTA',
      '4Depth': '',
      FILE: '/widgets/detail/cta/ProdStateCTA.tsx',
      PATH: '/shop/detail/pub?comp=cta',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 재입고알림(L)',
      '4Depth': '',
      FILE: '/widgets/detail/cta/AlramDialog.tsx',
      PATH: '/shop/detail/etc',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 공개 알림 신청(L)',
      '4Depth': '',
      FILE: '/widgets/detail/cta/AlramDialog.tsx',
      PATH: '/shop/detail/etc',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '햄퍼 CTA',
      '4Depth': '',
      FILE: '/widgets/detail/cta/drawer/CtaDrawer.tsx',
      PATH: '/shop/detail/pub?comp=cta',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-19',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '옥션 CTA',
      '4Depth': '',
      FILE: '/widgets/detail/cta/AuctionCTA.tsx',
      PATH: '/shop/detail/pub?comp=cta',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '래플 CTA',
      '4Depth': '',
      FILE: '/widgets/detail/cta/RaffleCTA.tsx',
      PATH: '/shop/detail/pub?comp=cta',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '라이브 CTA',
      '4Depth': '',
      FILE: '/widgets/detail/cta/LiveCTA.tsx',
      PATH: '/shop/detail/pub?comp=cta',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '구독 CTA',
      '4Depth': '',
      FILE: '/widgets/detail/cta/SubscriptionCTA.tsx',
      PATH: '/shop/detail/pub?comp=cta',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },

    {
      '1Depth': '',
      '2Depth': '예약 신청서 작성',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/detail/VisitReserveForm.tsx',
      PATH: '/shop/detail/visitreserve',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 주문정보수정(D)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/detail/VisitReserveFormDrawer.tsx',
      PATH: '/shop/detail/etc',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-02',
      최종수정일: '',
      비고: '',
    },

    // 상품 상세 - 정기 구독
    {
      '1Depth': '상세 유형',
      '2Depth': '정기 구독',
      '3Depth': '영역별 확인',
      '4Depth': '',
      FILE: '영역별 통합 처리 (수정 : 김효정)',
      PATH: '',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '2025-09-02',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 정기구독 설정 (L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/coupon/SubscriptionSettingsDialog.tsx',
      PATH: '/shop/detail/subscription/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 회차별 구성상품 보기 (L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/coupon/SubscriptionRoundProductDialog.tsx',
      PATH: '/shop/detail/subscription/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 상품 구매 정보 안내 (L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/coupon/ProductPurchaseDialog.tsx',
      PATH: '/shop/detail/subscription/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '신청서',
      '4Depth': '',
      FILE: '/shop/detail/subscription/SubscriptionForm.tsx',
      PATH: '/shop/detail/subscription/form',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '데이터 없는 경우',
      FILE: '/shop/detail/subscription/SubscriptionForm.tsx',
      PATH: '/shop/detail/subscription/form?status=empty',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '신청 완료',
      FILE: '/shop/detail/subscription/SubscriptionForm.tsx',
      PATH: '/shop/detail/subscription/form?status=complete',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '문화센터',
      '3Depth': '정보고시,CTA',
      '4Depth': '',
      FILE: '영역별 통합',
      PATH: '/shop/detail/culture',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-03',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '렌탈',
      '3Depth': 'CTA',
      '4Depth': '',
      FILE: '영역별 통합',
      PATH: '/shop/detail/rental',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-03',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '여행',
      '3Depth': '변경 파일',
      '4Depth': '',
      FILE: '55(상세영역), 57(여행아이콘), 67(날짜선택영역L), 68(시간상시)',
      PATH: '',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-09-23',
      최종수정일: '',
      비고: '',
    },
  ],
} as const;

export default shop;
