export const navTabNames = {
  common: '전체 페이지',
  display: '전시 모듈',
  free: 'Free Html',
} as const;

export const pageData = {
  common: {
    pages: [
      {
        '1Depth': '메인/공통/기타',
        '2Depth': '레이아웃',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: '/test',
        작업자: '정지우',
        상태: 'completed',
        완료일: '2025-05-29',
        최종수정일: null,
        비고: '로그인 후 메뉴 확인 /test?login',
      },
      {
        '1Depth': '',
        '2Depth': '샵인샵',
        '3Detph': '메뉴 조건처리 및 뒤로가기 버튼 추가 (Mobile)',
        '4Depth': '',
        FILE: '',
        PATH: '/test?ncp',
        작업자: '하윤정',
        상태: 'completed',
        완료일: '2025-09-08',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '메인',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: '/main',
        작업자: '최수연',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '⤷ 뉴스레터(L)',
        '3Detph': '',
        '4Depth': '',
        FILE: '/etc/NewsletterDialog.tsx',
        PATH: '/etc',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: '(L)팝업확인용 경로',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '⤷ 뉴스레터 구독 동의(L)',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '⤷ 제3자 정보제공(L)',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '⤷ 개인정보 국외이전 동의(L)',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '⤷ 로그인(L)',
        '3Detph': '',
        '4Depth': '',
        FILE: '/auth/login/LoginDialog.tsx',
        PATH: null,
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '⤷ 장바구니(L)',
        '3Detph': '',
        '4Depth': '',
        FILE: '/layout/components/HeaderCart.tsx',
        PATH: null,
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: '2025-10-15',
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '⤷ 장바구니 - 데이터 없는 경우(L)',
        '3Detph': '',
        '4Depth': '',
        FILE: '/layout/components/HeaderCart.tsx',
        PATH: null,
        작업자: '정지우',
        상태: 'completed',
        완료일: '2025-10-15',
        최종수정일: '',
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '⤷ 위시리스트(L)',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '⤷ 검색(L)',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: '정지우',
        상태: 'completed',
        완료일: '2025-05-29',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '',
        '3Detph': '검색결과',
        '4Depth': '',
        FILE: '/search/SearchResult.tsx',
        PATH: '/search',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '⤷ 국가선택(L)',
        '3Detph': '',
        '4Depth': '',
        FILE: '/country/ChangeCountryDialog.tsx',
        PATH: null,
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '',
        '3Detph': '국가선택',
        '4Depth': '',
        FILE: '/country/ChangeCountry.tsx',
        PATH: '/country',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '⤷ 서비스 가입사실 확인(L)',
        '3Detph': '',
        '4Depth': '',
        FILE: '/etc/GuaranteeDialog.tsx',
        PATH: null,
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '⤷ 이용약관(L)',
        '3Detph': '',
        '4Depth': '',
        FILE: '/policy/service/ServiceTermsDialog.tsx',
        PATH: null,
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '⤷ 개인정보 처리방침(L)',
        '3Detph': '',
        '4Depth': '',
        FILE: '/policy/private/PrivateTermsDialog.tsx',
        PATH: null,
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '에러페이지',
        '3Detph': '404',
        '4Depth': '',
        FILE: '/error/NotFound.tsx',
        PATH: '/error?component=NotFound',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '',
        '3Detph': '500',
        '4Depth': '',
        FILE: '/error/ServerError.tsx',
        PATH: '/error?component=ServerError',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '',
        '3Detph': '메일 수신거부',
        '4Depth': '',
        FILE: '/error/Unsubscribed.tsx',
        PATH: '/error?component=Unsubscribed',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '',
        '3Detph': '시스템 점검 안내',
        '4Depth': '',
        FILE: '/error/SystemCheck.tsx',
        PATH: '/error?component=SystemCheck',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '',
        '3Detph': '판매중단 상품',
        '4Depth': '',
        FILE: '/error/SaleStop.tsx',
        PATH: '/error?component=SaleStop',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '',
        '3Detph': '매장없음',
        '4Depth': '',
        FILE: '/error/NoStores.tsx',
        PATH: '/error?component=NoStores',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '회원/로그인',
        '2Depth': '로그인',
        '3Detph': '',
        '4Depth': '',
        FILE: '/auth/login/loginForm.tsx',
        PATH: '/login',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-04-18',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '⤷ 비회원주문조회',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-04-18',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '',
        '3Detph': '서비스 이용 동의',
        '4Depth': '',
        FILE: '/auth/login/ServiceAgreement.tsx',
        PATH: '/login/agreement',
        작업자: '하윤정',
        상태: 'completed',
        완료일: '2025-10-27',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '아이디 찾기',
        '3Detph': '',
        '4Depth': '',
        FILE: '/auth/find/FindId.tsx',
        PATH: '/find/id',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-04-18',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '아이디 찾기 결과',
        '4Depth': '성공',
        FILE: '/auth/find/FindIdResult.tsx',
        PATH: '/find/id/result?status=success',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-04-18',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '실패',
        FILE: 'auth/find/FindIdResult.tsx',
        PATH: '/find/id/result?status=fail',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-04-18',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '전체 아이디 찾기',
        '4Depth': '인증',
        FILE: '/auth/find/FindIdVerify.tsx',
        PATH: '/find/id/verify',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-04-17',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '완료',
        '4Depth': '',
        FILE: '/auth/find/FindIdComplete.tsx',
        PATH: '/find/id/complete',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-04-18',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '비밀번호 찾기',
        '3Detph': '',
        '4Depth': '',
        FILE: '/auth/find/FindPw.tsx',
        PATH: '/find/password',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-04-18',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '비밀번호 찾기 결과',
        '4Depth': '',
        FILE: '/auth/find/FindPwResult.tsx',
        PATH: '/find/password/result',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-04-18',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '비밀번호 변경하기',
        '4Depth': '',
        FILE: '/auth/find/FindPwChange.tsx',
        PATH: '/find/password/change',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-04-18',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '변경 완료',
        FILE: '/auth/find/FindPwComplete.tsx',
        PATH: '/find/password/complete',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-04-18',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '회원가입',
        '3Detph': '간편인증',
        '4Depth': '',
        FILE: '/auth/join/JoinStep1.tsx',
        PATH: '/join',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-04-18',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '⤷ 이메일이 없는 경우 가입안내(L)',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-29',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '개인계정 연결',
        FILE: '/auth/join/JoinConnect.tsx',
        PATH: '/join/connect',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-29',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '이메일 인증 완료 (공통)',
        FILE: '/auth/verify/EmailVerify.tsx',
        PATH: '/verify?status=success',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-04-16',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '이메일 인증 실패 (공통)',
        FILE: '/auth/verify/EmailVerify.tsx',
        PATH: '/verify?status=fail',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-04-16',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '개인정보 입력',
        '4Depth': '이메일 인증',
        FILE: '/auth/join/JoinStep2.tsx',
        PATH: '/join/register?method=email',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-04-18',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '카카오 인증',
        FILE: '/auth/join/JoinStep2KaKao.tsx',
        PATH: '/join/register/kakao?status=case1',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-04-18',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '카카오 인증 - 계정사용불가',
        FILE: '/auth/join/JoinStep2KaKao.tsx',
        PATH: '/join/register/kakao?status=case2',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-04-18',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '⤷ 이용약관 및 개인정보 처리방침(L)',
        '4Depth': '',
        FILE: '/policy/TermsDialog.tsx',
        PATH: null,
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '회원가입 완료',
        '4Depth': '',
        FILE: '/auth/join/JoinComplete.tsx',
        PATH: '/join/complete',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-04-17',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '휴면계정 복구 안내',
        '3Detph': '',
        '4Depth': '',
        FILE: '/auth/update/Account.tsx',
        PATH: '/update/account',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-04-18',
        최종수정일: null,
        비고: null,
      },
      // {
      //   '1Depth': null,
      //   '2Depth': '비밀번호 만료 안내',
      //   '3Detph': '',
      //   '4Depth': '',
      //   FILE: null,
      //   PATH: null,
      //   작업자: null,
      //   상태: 'waiting',
      //   완료일: null,
      //   최종수정일: null,
      //   비고: null,
      // },
      {
        '1Depth': null,
        '2Depth': '비밀번호 초기화 안내',
        '3Detph': '',
        '4Depth': '',
        FILE: '/auth/update/Password.tsx',
        PATH: '/update/password',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-04-18',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '위시리스트',
        '2Depth': '',
        '3Detph': '',
        '4Depth': '',
        FILE: '/mypage/widhlist/WishList.tsx',
        PATH: '/mypage/wishlist',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-05-09',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '⤷ 재입고알림신청(L)',
        '3Detph': '',
        '4Depth': '',
        FILE: '/product/components/RestockDialog.tsx',
        PATH: '',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-05-09',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '주문/장바구니',
        '2Depth': '장바구니',
        '3Detph': '',
        '4Depth': '',
        FILE: '/orders/Cart.tsx',
        PATH: '/orders/cart',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-05-08',
        최종수정일: '2025-10-15',
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '',
        '3Detph': '데이터 없음',
        '4Depth': '',
        FILE: '/orders/Cart.tsx',
        PATH: '/orders/cart?nodata',
        작업자: '정지우',
        상태: 'completed',
        완료일: '2025-10-15',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '주문 확인 및 결제',
        '3Detph': '주문 작성',
        '4Depth': '',
        FILE: '/orders/OrderForms.tsx',
        PATH: '/orders/forms',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-05-02',
        최종수정일: '2025-09-09',
        비고: '[0909] 결제수단 추가건',
      },
      {
        '1Depth': '',
        '2Depth': '',
        '3Detph': '⤷ 주문 요약 정보',
        '4Depth': '',
        FILE: '/orders/components/OrderItem.tsx',
        PATH: '',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-05-02',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '',
        '3Detph': '',
        '4Depth': '⤷ 배송지 정보',
        FILE: '/orders/components/DeliveryInfo.tsx',
        PATH: '',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-05-02',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '',
        '3Detph': '',
        '4Depth': '⤷ 배송지 목록',
        FILE: '/orders/components/DeliveryList.tsx',
        PATH: '',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-05-02',
        최종수정일: null,
        비고: null,
      },
      // {
      //   '1Depth': '',
      //   '2Depth': '',
      //   '3Detph': '',
      //   '4Depth': '⤷ 배송지 삭제(L)',
      //   FILE: '/orders/components/DeliveryList.tsx',
      //   PATH: '',
      //   작업자: '박성일',
      //   상태: 'completed',
      //   완료일: '2025-05-02',
      //   최종수정일: null,
      //   비고: null,
      // },
      {
        '1Depth': '',
        '2Depth': '',
        '3Detph': '',
        '4Depth': '⤷ 본인인증(L)',
        FILE: '/mypage/components/VerifyIdentity.tsx',
        PATH: '',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-05-02',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '',
        '3Detph': '⤷ 채무지급 보증안내 서비스 가입사실 확인(L)',
        '4Depth': '',
        FILE: '/orders/components/GuaranteeDialog.tsx',
        PATH: '',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-05-02',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '비회원 주문',
        '3Detph': '',
        '4Depth': '',
        FILE: '/orders/OrderForms.tsx',
        PATH: '/orders/forms?status=guest',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-05-07',
        최종수정일: null,
        비고: null,
      },
      // {
      //   '1Depth': '',
      //   '2Depth': '',
      //   '3Detph': '⤷ 주문 정보',
      //   '4Depth': '',
      //   FILE: '',
      //   PATH: '',
      //   작업자: '',
      //   상태: 'waiting',
      //   완료일: '',
      //   최종수정일: null,
      //   비고: null,
      // },
      // {
      //   '1Depth': '',
      //   '2Depth': '',
      //   '3Detph': '⤷ 결제 정보',
      //   '4Depth': '',
      //   FILE: '',
      //   PATH: '',
      //   작업자: '',
      //   상태: 'waiting',
      //   완료일: '',
      //   최종수정일: null,
      //   비고: null,
      // },
      // {
      //   '1Depth': '',
      //   '2Depth': '',
      //   '3Detph': '⤷ 비회원 주문 정보수집 동의(L)',
      //   '4Depth': '',
      //   FILE: '',
      //   PATH: '',
      //   작업자: '',
      //   상태: 'waiting',
      //   완료일: '',
      //   최종수정일: null,
      //   비고: null,
      // },
      {
        '1Depth': '',
        '2Depth': '주문 완료',
        '3Detph': '',
        '4Depth': '',
        FILE: '/orders/OrderComplete.tsx',
        PATH: '/orders/complete',
        작업자: '박성일',
        상태: 'completed',
        완료일: '2025-05-08',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '마이페이지',
        '2Depth': '주문/배송 조회',
        '3Detph': '목록',
        '4Depth': '',
        FILE: '/mypage/OrderList.tsx',
        PATH: '/mypage/orders',
        작업자: '정지우',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      // {
      //   '1Depth': null,
      //   '2Depth': '',
      //   '3Detph': '⤷ 옵션변경(L)',
      //   '4Depth': '',
      //   FILE: '/mypage/orders/OptionChangeDialog.tsx',
      //   PATH: null,
      //   작업자: '정지우',
      //   상태: 'completed',
      //   완료일: '2025-05-23',
      //   최종수정일: null,
      //   비고: null,
      // },
      // {
      //   '1Depth': null,
      //   '2Depth': '',
      //   '3Detph': '⤷ 예약주문안내(L)',
      //   '4Depth': '',
      //   FILE: '/mypage/orders/PreOrderGuideDialog.tsx',
      //   PATH: null,
      //   작업자: '정지우',
      //   상태: 'completed',
      //   완료일: '2025-05-23',
      //   최종수정일: null,
      //   비고: null,
      // },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '⤷ 배송추적(L)',
        '4Depth': '',
        FILE: '/mypage/orders/TrackDeliveryDialog.tsx',
        PATH: null,
        작업자: '정지우',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '상세',
        '4Depth': '',
        FILE: '/mypage/OrderDetail.tsx',
        PATH: '/mypage/orders/detail',
        작업자: '정지우',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '⤷ 주문상태 상세보기(L)',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: '정지우',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '⤷ 배송지 변경(L)',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: '정지우',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: '',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '⤷ 결제수단 변경(L)',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: '정지우',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: '',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '취소신청',
        '4Depth': '',
        FILE: '/mypage/OrderCancel.tsx',
        PATH: '/mypage/orders/cancel',
        작업자: '정지우',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: '2025-09-09',
        비고: '[0909] 반품 수정건으로 인한 UI 구조 수정',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '반품신청',
        '4Depth': '',
        FILE: '/mypage/OrderReturn.tsx',
        PATH: '/mypage/orders/return',
        작업자: '정지우',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: '2025-09-09',
        비고: '[0909] 반품 수정건',
      },
      // {
      //   '1Depth': null,
      //   '2Depth': '',
      //   '3Detph': '⤷ 계좌인증(L)',
      //   '4Depth': '',
      //   FILE: '',
      //   PATH: '',
      //   작업자: '정지우',
      //   상태: 'completed',
      //   완료일: '2025-05-23',
      //   최종수정일: null,
      //   비고: '',
      // },
      {
        '1Depth': null,
        '2Depth': '취소/반품',
        '3Detph': '목록',
        '4Depth': '',
        FILE: '/mypage/ReturnList.tsx',
        PATH: '/mypage/returns',
        작업자: '정지우',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: '',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '취소상세',
        '4Depth': '',
        FILE: '/mypage/OrderDetail.tsx',
        PATH: '/mypage/orders/detail',
        작업자: '정지우',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: '',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '반품상세',
        '4Depth': '',
        FILE: '/mypage/OrderDetail.tsx',
        PATH: '/mypage/orders/detail',
        작업자: '정지우',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: '',
      },
      {
        '1Depth': null,
        '2Depth': '영수증/세금계산서',
        '3Detph': '목록',
        '4Depth': '',
        FILE: '/mypage/receipt/Receipt.tsx',
        PATH: '/mypage/receipt',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: '',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '⤷ 영수증 출력(L)',
        '4Depth': '',
        FILE: '/mypage/receipt/PrintReceipt.tsx',
        PATH: null,
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '⤷ 세금계산서 출력(L)',
        '4Depth': '',
        FILE: '/mypage/receipt/PrintRecTax.tsx',
        PATH: null,
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '⤷ 카드전표 출력(L)',
        '4Depth': '',
        FILE: '/mypage/receipt/PrintRecCard.tsx',
        PATH: null,
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '⤷ 현금영수증 출력(L)',
        '4Depth': '',
        FILE: '/mypage/receipt/PrintRecCash.tsx',
        PATH: null,
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '⤷ 현금영수증 신청(L)',
        '4Depth': '',
        FILE: '',
        PATH: null,
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },

      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '⤷ 세금계산서 신청(L)',
        '4Depth': '',
        FILE: '/mypage/receipt/TaxInvoice.tsx',
        PATH: null,
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '회원정보변경',
        '3Detph': '비밀번호 인증(공통)',
        '4Depth': '',
        FILE: '/mypage/profile/Profile.tsx',
        PATH: '/mypage/profile',
        작업자: '하윤정',
        상태: 'completed',
        완료일: '2025-05-16',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '',
        '3Detph': '회원정보 변경 상세',
        '4Depth': '',
        FILE: '/mypage/profile/ProfileEdit.tsx',
        PATH: '/mypage/profile/edit',
        작업자: '하윤정',
        상태: 'completed',
        완료일: '2025-05-16',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': '',
        '2Depth': '',
        '3Detph': '⤷ 가려진 정보 보기(L)',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: '하윤정',
        상태: 'completed',
        완료일: '2025-05-16',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '회원탈퇴',
        '4Depth': '',
        FILE: '/mypage/profile/Leave.tsx',
        PATH: '/mypage/profile/leave',
        작업자: '하윤정',
        상태: 'completed',
        완료일: '2025-05-16',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '배송지관리',
        '3Detph': '관리',
        '4Depth': '',
        FILE: '/mypage/address/AddressManager.tsx',
        PATH: '/mypage/address',
        작업자: '하윤정',
        상태: 'completed',
        완료일: '2025-05-16',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '⤷ 목록',
        '4Depth': '',
        FILE: '/mypage/address/AddressBook.tsx',
        PATH: null,
        작업자: '하윤정',
        상태: 'completed',
        완료일: '2025-05-16',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '⤷ 추가/수정',
        '4Depth': '',
        FILE: '/mypage/address/AddressForm.tsx',
        PATH: null,
        작업자: '하윤정',
        상태: 'completed',
        완료일: '2025-05-16',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '⤷ 주소 검색(L)',
        '4Depth': '',
        FILE: '/mypage/address/AddressSearch.tsx',
        PATH: null,
        작업자: '하윤정',
        상태: 'completed',
        완료일: '2025-05-16',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '환불계좌/현금영수증',
        '3Detph': '',
        '4Depth': '',
        FILE: '/mypage/profile/AccountInfo.tsx',
        PATH: '/mypage/profile/account',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '⤷ 본인인증(L)',
        '4Depth': '',
        FILE: '/auth/components/UserAuthDialog.tsx',
        PATH: null,
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '예치금',
        '3Detph': '',
        '4Depth': '',
        FILE: '/mypage/deposit/Deposit.tsx',
        PATH: '/mypage/deposit',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '개인계정 연결관리',
        '3Detph': '',
        '4Depth': '',
        FILE: '/mypage/profile/SocialInfo.tsx',
        PATH: '/mypage/profile/social',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '1:1문의내역',
        '3Detph': '목록/상세',
        '4Depth': '',
        FILE: '/mypage/inquiry/InquiryList.tsx',
        PATH: '/mypage/inquiry',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '등록/수정',
        '4Depth': '',
        FILE: '/mypage/inquiry/InquiryForm.tsx',
        PATH: '/mypage/inquiry/register',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '⤷ 주문상품 찾기(L)',
        '4Depth': '',
        FILE: '/mypage/inquiry/OrderProdSearch.tsx',
        PATH: null,
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '등록완료',
        '4Depth': '',
        FILE: '/mypage/inquiry/InquiryComplete.tsx',
        PATH: '/mypage/inquiry/register/complete',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': 'Shop',
        '2Depth': "What's new",
        '3Detph': '신상품',
        '4Depth': '목록',
        FILE: '/product/shop/Shop.tsx',
        PATH: '/product/shop',
        작업자: '최수연',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '⤷ 필터',
        FILE: '/product/shop/ShopFilter.tsx',
        PATH: null,
        작업자: '최수연',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '제품 상세',
        FILE: '/product/detail/Product.tsx',
        PATH: '/product/detail',
        작업자: '최수연',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '⤷ 사이즈가이드(L)',
        FILE: '/product/components/SizeGuide.tsx',
        PATH: null,
        작업자: '최수연',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '⤷ 상품필수정보 제공고시(L)',
        FILE: '/product/detail/ProdAdditional.tsx',
        PATH: null,
        작업자: '최수연',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '⤷ 반품 및 환불 정책(L)',
        FILE: '/etc/ReturnPolicyDialog.tsx',
        PATH: null,
        작업자: '최수연',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '⤷ 재입고알림신청(L)',
        FILE: '/product/components/RestockDialog.tsx',
        PATH: '',
        작업자: '최수연',
        상태: 'completed',
        완료일: '2025-05-23',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': 'Best sellers',
        '3Detph': '이번주 인기 상품',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '파티웨어',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '이 시즌 컬러: 버건디',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': 'New year collection',
        '3Detph': 'New year collection',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': 'Clothing',
        '3Detph': '의류 모두 보기',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '아우터웨어',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '아우터 모두 보기',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '코트',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '자켓',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '블레이저',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '레더 자켓',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '니트 & 가디건',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '니트웨어 모두 보기',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '가디건',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '스웨터',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '캐시미어',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '터틀넥',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '블라우스 & 셔츠',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '블라우스 셔츠 모두 보기',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '블라우스',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '셔츠',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '탑 & 티셔츠',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '탑 모두 보기',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '베이직 티셔츠',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '롱 슬리브',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '스웻셔츠 후디',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '쇼트 슬리브',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '탱크탑 캐미솔',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '드레스',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '드레스 모두 보기',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '미니 드레스',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '미디 드레스',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '맥시 드레스',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '니트 드레스',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '파티 드레스',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '스커트',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '스커트 모두 보기',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '미니',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '미디',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '맥시',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '트라우저',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '트라우저 모두 보기',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '스트레이트핏 트라우저',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '와이드핏 트라우저',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '테일러드 트라우저',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '플레어핏 트라우저',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '쇼츠',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '데님',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '데님 모두 보기',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '스트레이트 ',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '와이드',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '플레어',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '슬림 핏',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '크롭',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '데님 쇼츠',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '점프수트',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '스윔웨어',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '스윔수트',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '비키니',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '파티웨어',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': 'Knitwear',
        '3Detph': '니트웨어 모두 보기',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '가디건',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '스웨터',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '캐시미어',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '터틀넥',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': 'Shoes',
        '3Detph': '슈즈 모두 보기',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '부츠',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '발레리나 & 플랫',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '펌프스',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '샌들',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '샌들 모두 보기',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '플랫 샌들',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '힐 샌들',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '로퍼',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': 'Bags',
        '3Detph': '백 모두 보기',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '숄더백',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '숄더백 모두 보기',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '버켓백',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '미니 숄더백',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '토트백',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '월렛',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '클러치',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': 'Accessories',
        '3Detph': '액세서리 모두 보기',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '겨울 액세서리',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '모자',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '모자 모두 보기',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '캡',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '비니',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '버킷햇',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '스카프',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '글러브',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '선글라스',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '벨트',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '헤어 액세서리',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '월렛',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '삭스 & 타이츠',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': 'Jewellery',
        '3Detph': '주얼리 모두 보기',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '이어링',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '링',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '네크리스',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '브레이슬릿',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': 'Beauty',
        '3Detph': '뷰티 모두 보기',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '바디케어',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '바디케어 모두 보기',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '바디 워시',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '바디 스크럽',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '바디 모이스춰라이저',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '핸드솝',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '핸드 로션',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '퍼퓸',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '메이크업',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '메이크업 모두 보기',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '립',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '아이 앤 브로우',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '페이스',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '',
        '4Depth': '브러쉬 툴',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '액세서리 & 툴',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '퍼퓸',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '네일',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': 'Fashion Stories',
        '3Detph': 'Bag destination',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': 'New year collection',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': 'New makeup range',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': 'Beloved bow bag',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': 'The gift guide',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': 'About',
        '2Depth': '',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: 'freeHtml',
      },
      {
        '1Depth': null,
        '2Depth': 'about us',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: 'freeHtml',
      },
      {
        '1Depth': null,
        '2Depth': '디자인협업(co-labs)',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: 'freeHtml',
      },
      {
        '1Depth': null,
        '2Depth': '지속가능성',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: 'freeHtml',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '단추에 깃든 가치',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: 'freeHtml',
      },
      {
        '1Depth': null,
        '2Depth': '재활용',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: 'freeHtml',
      },
      {
        '1Depth': null,
        '2Depth': '제품관리 방법',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: 'freeHtml',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '제품 관리방법(상세)',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: 'freeHtml',
      },
      {
        '1Depth': null,
        '2Depth': '제품 소재 안내',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: 'freeHtml',
      },
      {
        '1Depth': null,
        '2Depth': '',
        '3Detph': '지속 가능 컬렉션',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '전시모듈',
      },
      {
        '1Depth': null,
        '2Depth': '포용성&다양성',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: 'freeHtml',
      },
      {
        '1Depth': 'Contact',
        '2Depth': '매장 찾기',
        '3Detph': '',
        '4Depth': '',
        FILE: '/contact/StoreLocator.tsx',
        PATH: '/contact/locator',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '고객센터',
        '3Detph': '',
        '4Depth': '',
        FILE: '/contact/CustomerCenter.tsx',
        PATH: '/contact',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '채용정보',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '외부링크',
      },
      {
        '1Depth': null,
        '2Depth': '프레스미디어센터',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: '외부링크',
      },
      {
        '1Depth': '고객 서비스',
        '2Depth': '',
        '3Detph': '',
        '4Depth': '',
        FILE: '/service/CustomerService.tsx',
        PATH: '/service',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '고객센터',
        '3Detph': '',
        '4Depth': '',
        FILE: '/contact/CustomerCenter.tsx',
        PATH: '/contact',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '1:1 문의',
        '3Detph': '',
        '4Depth': '',
        FILE: '/mypage/inquiry/InquiryList.tsx',
        PATH: '/mypage/inquiry',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '매장 찾기',
        '3Detph': '',
        '4Depth': '',
        FILE: '/contact/StoreLocator.tsx',
        PATH: '/contact/locator',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '쇼핑 방법',
        '3Detph': '',
        '4Depth': '',
        FILE: '/service/how/HowToShop.tsx',
        PATH: '/service/how',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '사이즈 가이드',
        '3Detph': '',
        '4Depth': '',
        FILE: '/service/guide/SizeGuide.tsx',
        PATH: '/service/guide',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '기프트 카드',
        '3Detph': '',
        '4Depth': '',
        FILE: '/service/gift/GiftCard.tsx',
        PATH: '/service/gift',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '제품 케어',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: 'freeHtml',
      },
      {
        '1Depth': null,
        '2Depth': '리사이클링',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: null,
        작업자: null,
        상태: 'removed',
        완료일: null,
        최종수정일: null,
        비고: 'freeHtml',
      },
      {
        '1Depth': null,
        '2Depth': '배송안내',
        '3Detph': '',
        '4Depth': '',
        FILE: '/service/delivery/DeliveryMethods.tsx',
        PATH: '/service/delivery',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '반품 및 환불',
        '3Detph': '',
        '4Depth': '',
        FILE: '/policy/return/ReturnRefundPolicy.tsx',
        PATH: '/policy/return',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '결제 정보',
        '3Detph': '',
        '4Depth': '',
        FILE: '/service/payment/PaymentOptions.tsx',
        PATH: '/service/payment',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '이용약관',
        '3Detph': '',
        '4Depth': '',
        FILE: '/policy/service/ServicePolicy.tsx',
        PATH: '/policy/service',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '개인정보 처리방침',
        '3Detph': '',
        '4Depth': '',
        FILE: '/policy/private/PrivatePolicy.tsx',
        PATH: '/policy/private',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '포용성 & 다양성',
        '3Detph': '',
        '4Depth': '',
        FILE: '/service/inclusion/InclusionDiversity.tsx',
        PATH: '/service/inclusion',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
      {
        '1Depth': null,
        '2Depth': '시스템 점검 안내',
        '3Detph': '',
        '4Depth': '',
        FILE: '/service/system/SystemCheck.tsx',
        PATH: '/service/system',
        작업자: '채은미',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: null,
      },
    ],
  },
  display: {
    pages: [
      {
        컴포넌트: 'ImageHeroComponent',
        설명: '템플릿 1컬럼',
        PATH: '/main/display?component=imageHero',
        작업자: '최수연',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: '',
      },
      {
        컴포넌트: 'TextHeroComponent',
        설명: '템플릿 텍스트',
        PATH: '/main/display?component=textHero',
        작업자: '최수연',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: '',
      },
      {
        컴포넌트: 'MultiHeroComponent',
        설명: '템플릿 이미지 비디오 CTA',
        PATH: '/main/display?component=multiHero',
        작업자: '최수연',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: '',
      },
      // {
      //   컴포넌트: 'tmplFreeHtml',
      //   설명: '템플릿 Free HTML',
      //   PATH: '',
      //   작업자: null,
      //   상태: 'removed',
      //   완료일: '',
      //   최종수정일: null,
      //   비고: '',
      // },
      {
        컴포넌트: 'tmplTwoColumn',
        설명: '템플릿 2 컬럼',
        PATH: '/main/display?component=tmplTwoColumn',
        작업자: '최수연',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: '',
      },
      {
        컴포넌트: 'tmplThreeColumn',
        설명: '템플릿 3 컬럼 (모바일-세로)',
        PATH: '/main/display?component=tmplThreeColumn',
        작업자: '최수연',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: '',
      },
      {
        컴포넌트: 'tmplFourColumn',
        설명: '템플릿 4 컬럼',
        PATH: '/main/display?component=tmplFourColumn',
        작업자: '최수연',
        상태: 'completed',
        완료일: '2025-05-28',
        최종수정일: null,
        비고: '',
      },
      {
        컴포넌트: 'FreeHtml',
        설명: 'Free Html',
        PATH: '/main/display?component=FreeHtml',
        작업자: '채은미',
        상태: 'completed',
        완료일: '',
        최종수정일: '',
        비고: '',
      },
    ],
  },
  free: {
    pages: [
      {
        '1Depth': 'Free Html Guide',
        '2Depth': '',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: '/free/sample',
        작업자: null,
        상태: 'removed',
        완료일: '',
        최종수정일: null,
        비고: '',
      },
      {
        '1Depth': 'About',
        '2Depth': '',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: '/free/about',
        작업자: '채은미',
        상태: 'completed',
        완료일: null,
        최종수정일: null,
        비고: '',
      },
      {
        '1Depth': '',
        '2Depth': 'about us',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: '/free/about/aboutUs',
        작업자: '채은미',
        상태: 'completed',
        완료일: null,
        최종수정일: null,
        비고: '',
      },
      {
        '1Depth': '',
        '2Depth': '디자인협업(co-labs)',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: '/free/about/coLabs',
        작업자: '채은미',
        상태: 'completed',
        완료일: null,
        최종수정일: null,
        비고: '',
      },
      {
        '1Depth': '',
        '2Depth': '지속가능성',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: '/free/about/sustainability',
        작업자: '채은미',
        상태: 'completed',
        완료일: null,
        최종수정일: null,
        비고: '',
      },
      {
        '1Depth': '',
        '2Depth': '',
        '3Detph': '단추에 깃든 가치',
        '4Depth': '',
        FILE: null,
        PATH: '/free/about/sustainability/buttonsImpact',
        작업자: '채은미',
        상태: 'completed',
        완료일: null,
        최종수정일: null,
        비고: '',
      },
      {
        '1Depth': '',
        '2Depth': '재활용',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: '/free/about/recycling',
        작업자: '채은미',
        상태: 'completed',
        완료일: null,
        최종수정일: null,
        비고: '',
      },
      {
        '1Depth': '',
        '2Depth': '제품관리 방법',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: '/free/about/care',
        작업자: '채은미',
        상태: 'completed',
        완료일: null,
        최종수정일: null,
        비고: '',
      },
      {
        '1Depth': '',
        '2Depth': '',
        '3Detph': '제품 관리방법(상세)',
        '4Depth': '',
        FILE: null,
        PATH: '/free/about/care/detail',
        작업자: '채은미',
        상태: 'completed',
        완료일: null,
        최종수정일: null,
        비고: '',
      },
      {
        '1Depth': '',
        '2Depth': '제품 소재 안내',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: '/free/about/materials',
        작업자: '채은미',
        상태: 'completed',
        완료일: null,
        최종수정일: null,
        비고: '',
      },
      {
        '1Depth': '',
        '2Depth': '포용성&다양성',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: '/free/about/inclusionDiversity',
        작업자: '채은미',
        상태: 'completed',
        완료일: null,
        최종수정일: null,
        비고: '',
      },
      {
        '1Depth': '고객 서비스',
        '2Depth': '제품 케어',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: '/free/about/care',
        작업자: '채은미',
        상태: 'completed',
        완료일: null,
        최종수정일: null,
        비고: 'about과 동일',
      },
      {
        '1Depth': '',
        '2Depth': '리사이클링',
        '3Detph': '',
        '4Depth': '',
        FILE: null,
        PATH: '/free/about/recycling',
        작업자: '채은미',
        상태: 'completed',
        완료일: null,
        최종수정일: null,
        비고: 'about과 동일',
      },
    ],
  },
} as const;
