const community = {
  pages: [
    {
      '1Depth': 'MeSpace',
      '2Depth': '메인',
      '3Depth': '',
      '4Depth': '',
      FILE: '/mespace/MeSpace',
      PATH: '/mespace',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-05',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 마이페이지',
      '3Depth': '',
      '4Depth': '',
      FILE: '/mespace/MeSpace',
      PATH: '/mespace?type=my',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-05',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '상품(D)',
      '4Depth': '',
      FILE: '/widgets/mespace/MeCardList',
      PATH: '',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-05',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '컬렉션(D)',
      '4Depth': '',
      FILE: '/widgets/mespace/MeBar',
      PATH: '',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-05',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '투표-상품, 브랜드, 일반(D)',
      '4Depth': '',
      FILE: '/widgets/mespace/MeBar',
      PATH: '',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-05',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '댓글/대댓글(D)',
      '4Depth': '',
      FILE: '/widgets/mespace/MeComment',
      PATH: '',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-05',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '글쓰기',
      '3Depth': '',
      '4Depth': '',
      FILE: '/mespace/MeCreate',
      PATH: '/mespace/create',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-05',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '투표 종료 - 상품',
      '4Depth': '',
      FILE: '/mespace/MeCreate',
      PATH: '/mespace/create?type=vote&vote=product&disabled',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-05',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '투표 종료 - 브랜드',
      '4Depth': '',
      FILE: '/mespace/MeCreate',
      PATH: '/mespace/create?type=vote&vote=brand&disabled',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-05',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '투표 종료 - 직접입력',
      '4Depth': '',
      FILE: '/mespace/MeCreate',
      PATH: '/mespace/create?type=vote&vote=direct&disabled',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-05',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '리뷰 추가',
      '4Depth': '',
      FILE: '/mespace/MeAddReview',
      PATH: '/mespace/add/review',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-05',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '브랜드 추가',
      '4Depth': '',
      FILE: '/mespace/MeAddBrand',
      PATH: '/mespace/add/brand',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-05',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '컬렉션 추가',
      '4Depth': '',
      FILE: '/mespace/MeAddCollection',
      PATH: '/mespace/add/collection',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-05',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '상품추가',
      '4Depth': '',
      FILE: '/mespace/MeAddProduct',
      PATH: '/mespace/add/product',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-05',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '타 컨텐츠 내 연계 영역',
      '3Depth': '',
      '4Depth': '',
      FILE: '/mespace/MeSpaceDialog',
      PATH: '/mespace/etc',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-05',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': 'GEM',
      '2Depth': 'PRODUCT',
      '3Depth': '',
      '4Depth': '',
      FILE: '/gem/gem/product/ProductGemList',
      PATH: '/gem/gem',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': 'GEM한 상품 없는 경우',
      '4Depth': '',
      FILE: '/gem/gem/product/ProductGemList',
      PATH: '/gem/gem?tab=product&nodata',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'BRAND',
      '3Depth': '',
      '4Depth': '',
      FILE: '/gem/gem/brand/BrandGemList',
      PATH: '/gem/gem?tab=brand',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': 'GEM한 브랜드 없는 경우',
      '4Depth': '',
      FILE: '/gem/gem/brand/BrandGemList',
      PATH: '/gem/gem?tab=brand&nodata',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'COLLECTION',
      '3Depth': '',
      '4Depth': '',
      FILE: '/gem/gem/collection/CollectionGemList',
      PATH: '/gem/gem?tab=collection',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': 'GEM한 컬렉션 없는 경우',
      '4Depth': '',
      FILE: '/gem/gem/collection/CollectionGemList',
      PATH: '/gem/gem?tab=collection&nodata',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'PEOPLE',
      '3Depth': '',
      '4Depth': '',
      FILE: '/gem/gem/people/PeopleGemList',
      PATH: '/gem/gem?tab=people',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': 'GEM한 유저 없는 경우',
      '4Depth': '',
      FILE: '/gem/gem/people/PeopleGemList',
      PATH: '/gem/gem?tab=people&nodata',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': 'MY COLLECTION',
      '2Depth': '목록',
      '3Depth': '',
      '4Depth': '',
      FILE: '/gem/mycollection/MycollectionList',
      PATH: '/gem/mycollection',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '생성한 컬렉션이 0건일 때 ',
      '4Depth': '',
      FILE: '/gem/mycollection/MycollectionList',
      PATH: '/gem/mycollection?nodata',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '상세',
      '3Depth': 'Case 1. 내 컬렉션 상세',
      '4Depth': '공개 상태',
      FILE: '/gem/mycollection/detail/DetailMyCollection',
      PATH: '/gem/mycollection/detail?case1',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '비공개 상태',
      FILE: '/gem/mycollection/detail/DetailMyCollection',
      PATH: '/gem/mycollection/detail?lock',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': 'Case 2. 타인 컬렉션 상세',
      '4Depth': '',
      FILE: '/gem/mycollection/detail/DetailMyCollection',
      PATH: '/gem/mycollection/detail?case2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '생성한 컬렉션 내 항목이 0건일 때',
      '4Depth': '',
      FILE: '/gem/mycollection/detail/DetailMyCollection',
      PATH: '/gem/mycollection/detail?nodata',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '컬렉션명 편집',
      '4Depth': '',
      FILE: '/gem/mycollection/detail/edit/EditCollectionName',
      PATH: '/gem/mycollection/detail/edit',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '항목 삭제 (L)',
      '4Depth': '',
      FILE: '/gem/mycollection/addremove/DeleteItemDialog',
      PATH: '/gem/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '생성',
      '3Depth': 'Step1. 컬렉션명 입력',
      '4Depth': '',
      FILE: '/gem/mycollection/create/CreateStep1',
      PATH: '/gem/mycollection/create/name',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': 'Step2. 항목 추가',
      '4Depth': '',
      FILE: '/gem/mycollection/create/CreateStep2',
      PATH: '/gem/mycollection/create/additems',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '상품과 브랜드 동시에 0건일 때',
      FILE: '/gem/mycollection/create/CreateStep2',
      PATH: '/gem/mycollection/create/additems?nodata=all',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '상품만 0건일 때',
      FILE: '/gem/mycollection/create/CreateStep2',
      PATH: '/gem/mycollection/create/additems?nodata=product',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '브랜드만 0건일 때',
      FILE: '/gem/mycollection/create/CreateStep2',
      PATH: '/gem/mycollection/create/additems?nodata=brand',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': 'Step 3. 컬렉션 공개 설정',
      '4Depth': '',
      FILE: '/gem/mycollection/create/CreateStep3',
      PATH: '/gem/mycollection/create/visibility',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '항목추가',
      '2Depth': 'Case 1. 상품/브랜드 GEM 시 추가',
      '3Depth': '컬렉션 선택 (D)',
      '4Depth': '',
      FILE: '/gem/mycollection/components/SelectCollectionDrawer',
      PATH: '/gem/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'Case 2. GEM 페이지에서 추가',
      '3Depth': '컬렉션에 상품 추가 (L)',
      '4Depth': '',
      FILE: '/gem/mycollection/addremove/AddProductDialog',
      PATH: '/gem/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '컬렉션에 브랜드 추가 (L)',
      '4Depth': '',
      FILE: '/gem/mycollection/addremove/AddBrandDialog',
      PATH: '/gem/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '컬렉션 선택 (D)',
      '4Depth': '',
      FILE: '/gem/mycollection/addremove/SelectCollectionDrawer',
      PATH: '/gem/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'Case 3. 컬렉션 상세 페이지에서 추가',
      '3Depth': '항목 추가 (L)',
      '4Depth': '',
      FILE: '/gem/mycollection/addremove/AddItemDialog',
      PATH: '/gem/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
  ],
} as const;

export default community;
