const common = {
  pages: [
    {
      '1Depth': '레이아웃',
      '2Depth': '',
      '3Depth': '',
      FILE: '',
      PATH: '/test',
      작업자: '최수연',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ Header',
      '3Depth': '',
      FILE: '/widgets/layout/Header.tsx',
      PATH: '',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ Footer',
      '3Depth': '',
      FILE: '/widgets/layout/Footer.tsx',
      PATH: '',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ Navigation Bar',
      '3Depth': '',
      FILE: '/widgets/layout/NavigationBar.tsx',
      PATH: '',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ FAB',
      '3Depth': '',
      FILE: '/widgets/layout/FAB.tsx',
      PATH: '',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 앱 다운로드 유도 배너',
      '3Depth': '',
      FILE: '/widgets/layout/PromotionBar.tsx',
      PATH: '',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 앱 다운로드 팝업(L)',
      '3Depth': '',
      FILE: '/widgets/etc/AppDownloadDialog.tsx',
      PATH: '',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 앱 접근 권한 안내 팝업(L)',
      '3Depth': '',
      FILE: '/widgets/etc/AppAccessDialog.tsx',
      PATH: '',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '약관',
      '2Depth': '이용약관',
      '3Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '콘텐츠 수급 예정',
    },
    {
      '1Depth': '',
      '2Depth': '개인정보 처리방침',
      '3Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '콘텐츠 수급 예정',
    },
    {
      '1Depth': '',
      '2Depth': '청소년보호정책',
      '3Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '콘텐츠 수급 예정',
    },
    {
      '1Depth': '이메일',
      '2Depth': '[일반] 주문완료',
      '3Depth': '주문 시, 결제수단 [무통장입금] CASE',
      FILE: '/public/email/EML-00101.html',
      PATH: '/email/EML-00101.html',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '주문 시, 결제수단 [상품권결제] CASE',
      FILE: '/public/email/EML-00102.html',
      PATH: '/email/EML-00102.html',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '결제완료 - 배송지 1곳  CASE',
      FILE: '/public/email/EML-00201.html',
      PATH: '/email/EML-00201.html',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '결제완료 - 배송지 멀티  CASE ',
      FILE: '/public/email/EML-00202.html',
      PATH: '/email/EML-00202.html',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '[선물] 주문서',
      '3Depth': '받는 분 1명 인   CASE ',
      FILE: '/public/email/EML-00203.html',
      PATH: '/email/EML-00203.html',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[선물픽] 받는 분 1명 인   CASE ',
      FILE: '/public/email/EML-00204.html',
      PATH: '/email/EML-00204.html',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[선물] 받는 분 멀티 인   CASE ',
      FILE: '/public/email/EML-00205.html',
      PATH: '/email/EML-00205.html',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '[일반] 주문서',
      '3Depth': 'e쿠폰/이용권 주문완료 시',
      FILE: '/public/email/EML-00206.html',
      PATH: '/email/EML-00206.html',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '문화센터 주문완료 시',
      FILE: '/public/email/EML-00207.html',
      PATH: '/email/EML-00207.html',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '[0원결제] 주문서',
      '3Depth': '상담후결제, 계약금/잔금 - 주문완료 시',
      FILE: '/public/email/EML-00208.html',
      PATH: '/email/EML-00208.html',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '방문쿠폰 주문완료',
      '3Depth': '상품상세 [쿠폰받기] 클릭 시 발급완료',
      FILE: '/public/email/EML-00209.html',
      PATH: '/email/EML-00209.html',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '상품상세 [예약하기] 클릭 시 신청완료',
      FILE: '/public/email/EML-00210.html',
      PATH: '/email/EML-00210.html',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '[0원결제] 주문서',
      '3Depth': '상품상세 [신청하기] 클릭 시 신청완료',
      FILE: '/public/email/EML-00211.html',
      PATH: '/email/EML-00211.html',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
  ],
} as const;

export default common;
