const display = {
  pages: [
    {
      '모듈 ID': '공통',
      전시타입: '공통 유닛 - 타이틀',
      FILE: '/widgets/display/Sample.tsx',
      PATH: '/display?component=title',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-07-10',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': '공통',
      전시타입: '상품 유닛 - 세로형',
      FILE: '/widgets/display/Sample.tsx',
      PATH: '/display?component=vertical',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-07-10',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': '공통',
      전시타입: '상품 유닛 - 가로형',
      FILE: '/widgets/display/Sample.tsx',
      PATH: '/display?component=horizontal',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-07-10',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_001',
      전시타입: '세로형 메인배너',
      FILE: '/widgets/display/MLBN001.tsx',
      PATH: '/display?component=MLBN001',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_002',
      전시타입: '세로형 메인배너2',
      FILE: '/widgets/display/MLBN002.tsx',
      PATH: '/display?component=MLBN002',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_004',
      전시타입: '세로 중앙정렬형 전면 메인배너',
      FILE: '/widgets/display/MLBN004.tsx',
      PATH: '/display?component=MLBN004',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_005',
      전시타입: '가로형 이미지 배너',
      FILE: '/widgets/display/MLBN005.tsx',
      PATH: '/display?component=MLBN005',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_006_1',
      전시타입: '정방형 2열 중앙 타이틀 배너',
      FILE: '/widgets/display/MLBN006_1.tsx',
      PATH: '/display?component=MLBN006_1',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_006_2',
      전시타입: '탭+정방형 2열 중앙 타이틀 배너',
      FILE: '/widgets/display/MLBN006_2.tsx',
      PATH: '/display?component=MLBN006_2',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_006_3',
      전시타입: '탭+정방형 2열 외부 타이틀 배너',
      FILE: '/widgets/display/MLBN006_3.tsx',
      PATH: '/display?component=MLBN006_3',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_007',
      전시타입: '정방형 2열 외부 타이틀 배너',
      FILE: '/widgets/display/MLBN007.tsx',
      PATH: '/display?component=MLBN007',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_008',
      전시타입: '1단 가로 리스트 배너',
      FILE: '/widgets/display/MLBN008.tsx',
      PATH: '/display?component=MLBN008',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_009',
      전시타입: '가로형 1단 롤링 배너',
      FILE: '/widgets/display/MLBN009.tsx',
      PATH: '/display?component=MLBN009',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_009_1',
      전시타입: '가로형 1단 롤링 배너',
      FILE: '/widgets/display/MLBN009_1.tsx',
      PATH: '/display?component=MLBN009_1',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-07-08',
      최종수정일: null,
      비고: '샵메인',
    },
    {
      '모듈 ID': 'ML_BN_010',
      전시타입: '중앙정렬 좌/우 스와이프 3단 배너',
      FILE: '/widgets/display/MLBN010.tsx',
      PATH: '/display?component=MLBN010',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_011',
      전시타입: '1단 띠 배너 롤링 타입',
      FILE: '/widgets/display/MLBN011.tsx',
      PATH: '/display?component=MLBN011',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_012',
      전시타입: '1단 띠 배너 리스트 타입',
      FILE: '/widgets/display/MLBN012.tsx',
      PATH: '/display?component=MLBN012',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_014',
      전시타입: '플리킹 이미지+ 영상 배너',
      FILE: '/widgets/display/MLBN014.tsx',
      PATH: '/display?component=MLBN014',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_016',
      전시타입: '1열 탭형 배너',
      FILE: '/widgets/display/MLBN016.tsx',
      PATH: '/display?component=MLBN016',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_017',
      전시타입: '세로형 1.5 스와이프 배너',
      FILE: '/widgets/display/MLBN017.tsx',
      PATH: '/display?component=MLBN017',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_019',
      전시타입: '좌/우 스크롤 2.5단 세로 배너',
      FILE: '/widgets/display/MLBN019.tsx',
      PATH: '/display?component=MLBN019',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_023',
      전시타입: '아이콘+키워드 형 좌/우 스크롤 배너',
      FILE: '/widgets/display/MLBN023.tsx',
      PATH: '/display?component=MLBN023',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_024',
      전시타입: '5열 고정 아이콘 배너',
      FILE: '/widgets/display/MLBN024.tsx',
      PATH: '/display?component=MLBN024',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_025_1',
      전시타입: '4열 아이콘 배너 리스트',
      FILE: '/widgets/display/MLBN025_1.tsx',
      PATH: '/display?component=MLBN025_1',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_025_2',
      전시타입: '3열 아이콘 배너 리스트',
      FILE: '/widgets/display/MLBN025_2.tsx',
      PATH: '/display?component=MLBN025_2',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_025_3',
      전시타입: '4열 아이콘 배너 아코디언 리스트',
      FILE: '/widgets/display/MLBN025_3.tsx',
      PATH: '/display?component=MLBN025_3',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_026',
      전시타입: '좌/우 스크롤 4.5열 아이콘 배너',
      FILE: '/widgets/display/MLBN026.tsx',
      PATH: '/display?component=MLBN026',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_027',
      전시타입: '세로 1.5 더보기 배너',
      FILE: '/widgets/display/MLBN027.tsx',
      PATH: '/display?component=MLBN027',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_028',
      전시타입: '가로 1.5 스와이프 배너',
      FILE: '/widgets/display/MLBN028.tsx',
      PATH: '/display?component=MLBN028',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_029',
      전시타입: '가로 1.5 스와이프 더보기 배너',
      FILE: '/widgets/display/MLBN029.tsx',
      PATH: '/display?component=MLBN029',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: 'Spec Out',
    },
    {
      '모듈 ID': 'ML_BN_030',
      전시타입: '가로 리스트 배너',
      FILE: '/widgets/display/MLBN030.tsx',
      PATH: '/display?component=MLBN030',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_031',
      전시타입: '세로 1.5 스와이프 플래그 배너',
      FILE: '/widgets/display/MLBN031.tsx',
      PATH: '/display?component=MLBN031',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BN_032',
      전시타입: '2열 텍스트 배너',
      FILE: '/widgets/display/MLBN032.tsx',
      PATH: '/display?component=MLBN032',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: 'Spec Out',
    },
    {
      '모듈 ID': 'ML_BN_034',
      전시타입: '(기획 수정 예정)',
      FILE: '/widgets/display/MLBN034.tsx',
      PATH: '/display?component=MLBN034',
      작업자: '하윤정',
      상태: 'progress',
      완료일: '2025-07-18',
      최종수정일: null,
      비고: '샵메인',
    },
    {
      '모듈 ID': 'ML_BN_036',
      전시타입: '이미지내 텍스트 노출형 좌/우 스크롤 2.5단 세로 배너',
      FILE: '/widgets/display/MLBN036.tsx',
      PATH: '/display?component=MLBN036',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-07-08',
      최종수정일: null,
      비고: '샵메인',
    },
    {
      '모듈 ID': 'ML_BN_037',
      전시타입: '텍스트 배너',
      FILE: '/widgets/display/MLBN037.tsx',
      PATH: '/display?component=MLBN037',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: '쇼룸 모아보기',
    },
    {
      '모듈 ID': 'ML_BN_038',
      전시타입: '가로 리스트 배너 박스형(샵메인)',
      FILE: '/widgets/display/MLBN038.tsx',
      PATH: '/display?component=MLBN038',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-07-08',
      최종수정일: null,
      비고: '샵메인',
    },
    {
      '모듈 ID': 'ML_BN_041',
      전시타입: '(기획 수정 예정)',
      FILE: '/widgets/display/MLBN041.tsx',
      PATH: '/display?component=MLBN041',
      작업자: '하윤정',
      상태: 'progress',
      완료일: '2025-07-18',
      최종수정일: null,
      비고: '샵메인',
    },
    {
      '모듈 ID': 'ML_BNPD_001_1',
      전시타입: '배너 탭 2.5 스와이프 상품',
      FILE: '/widgets/display/MLBNPD001_1.tsx',
      PATH: '/display?component=MLBNPD001_1',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BNPD_001_2',
      전시타입: '배너 + 2.5 가로 스크롤 상품',
      FILE: '/widgets/display/MLBNPD001_2.tsx',
      PATH: '/display?component=MLBNPD001_2',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BNPD_002',
      전시타입: '가로배너+가로 더보기 상품',
      FILE: '/widgets/display/MLBNPD002.tsx',
      PATH: '/display?component=MLBNPD002',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-06-24',
      최종수정일: '2025-07-15',
      비고: '셔플 제거 및 더보기 수정',
    },
    {
      '모듈 ID': 'ML_BNPD_003',
      전시타입: '세로배너+1.5 가로 스와이프 상품',
      FILE: '/widgets/display/MLBNPD003.tsx',
      PATH: '/display?component=MLBNPD003',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BNPD_004',
      전시타입: '세로배너 중앙 정렬 1열 리스트 가로 상품',
      FILE: '/widgets/display/MLBNPD004.tsx',
      PATH: '/display?component=MLBNPD004',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-07-07',
      최종수정일: '2025-07-17',
      비고: '서브 타이틀 삭제',
    },
    {
      '모듈 ID': 'ML_BNPD_006',
      전시타입: '탭 가로배너 3열 이미지 단일 상품',
      FILE: '/widgets/display/MLBNPD006.tsx',
      PATH: '/display?component=MLBNPD006',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_BNPD_007',
      전시타입: '탭 세로배너 3열 상품',
      FILE: '/widgets/display/MLBNPD007.tsx',
      PATH: '/display?component=MLBNPD007',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_LIVE_001',
      전시타입: '라이브 캘린더 모듈',
      FILE: '/widgets/display/MLLIVE001.tsx',
      PATH: '/display?component=MLLIVE001',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_LIVE_002',
      전시타입: '1.5열 상품 밖 라이브 리스트',
      FILE: '/widgets/display/MLLIVE002.tsx',
      PATH: '/display?component=MLLIVE002',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_PD_001',
      전시타입: '2단 2.5열 상품',
      FILE: '/widgets/display/MLPD001.tsx',
      PATH: '/display?component=MLPD001',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-06-24',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_PD_004',
      전시타입: '2단 탭 2.5열 상품모듈',
      FILE: '/widgets/display/MLPD004.tsx',
      PATH: '/display?component=MLPD004',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-07-07',
      최종수정일: '',
      비고: '',
    },
    {
      '모듈 ID': 'ML_PD_007',
      전시타입: '3열 탭 상품모듈',
      FILE: '/widgets/display/MLPD007.tsx',
      PATH: '/display?component=MLPD007',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-06-24',
      최종수정일: '2025-07-15',
      비고: '셔플 제거 및 더보기 수정',
    },
    {
      '모듈 ID': 'ML_PD_010',
      전시타입: '1.5열 플래그 +  스와이프 배너',
      FILE: '/widgets/display/MLPD010.tsx',
      PATH: '/display?component=MLPD010',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_PD_015_1',
      전시타입: '2열 탭+가격필터 상품',
      FILE: '/widgets/display/MLPD015_1.tsx',
      PATH: '/display?component=MLPD015_1',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_PD_015_2',
      전시타입: '2열 전체 필터 상품',
      FILE: '/widgets/display/MLPD015_2.tsx',
      PATH: '/display?component=MLPD015_2',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_VDO_001',
      전시타입: '2.5열 숏폼 리스트',
      FILE: '/widgets/display/MLVDO001.tsx',
      PATH: '/display?component=MLVDO001',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_VDO_002',
      전시타입: '1.5열 상품 안 라이브 리스트',
      FILE: '/widgets/display/MLVDO002.tsx',
      PATH: '/display?component=MLVDO002',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_VDO_007_1',
      전시타입: '1열 전체 숏폼',
      FILE: '/widgets/display/MLVDO007_1.tsx',
      PATH: '/display?component=MLVDO007_1',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_VDO_007_2',
      전시타입: '1.5열 가로스크롤 숏폼',
      FILE: '/widgets/display/MLVDO007_2.tsx',
      PATH: '/display?component=MLVDO007_2',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_VDO_007_3',
      전시타입: '2열 세로리스트 숏폼',
      FILE: '/widgets/display/MLVDO007_3.tsx',
      PATH: '/display?component=MLVDO007_3',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-07-07',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'D_ML_BNPD_002',
      전시타입: '가로배너+가로 더보기 상품',
      FILE: '/widgets/display/DMLBNPD002.tsx',
      PATH: '/display?component=DMLBNPD002',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-08-01',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'D_ML_BNPD_003',
      전시타입: '세로배너+1.5 가로 스와이프 상품',
      FILE: '/widgets/display/DMLBNPD003.tsx',
      PATH: '/display?component=DMLBNPD003',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-08-01',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'D_ML_BNPD_009',
      전시타입: '본문형 가로배너',
      FILE: '/widgets/display/DMLBNPD009.tsx',
      PATH: '/display?component=DMLBNPD009',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-08-01',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'D_ML_BN_025_2',
      전시타입: '3열 아이콘 배너 리스트',
      FILE: '/widgets/display/DMLBN025_2.tsx',
      PATH: '/display?component=DMLBN025_2',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-08-01',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'D_ML_BN_025_1',
      전시타입: '4열 아이콘 배너 리스트',
      FILE: '/widgets/display/DMLBN025_1.tsx',
      PATH: '/display?component=DMLBN025_1',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-08-01',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'D_ML_BN_024',
      전시타입: '좌/우 스크롤 5열 고정 아이콘  배너',
      FILE: '/widgets/display/DMLBN024.tsx',
      PATH: '/display?component=DMLBN024',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-08-01',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'D_ML_BNPD_007',
      전시타입: '탭 세로배너 3열 상품',
      FILE: '/widgets/display/DMLBNPD007.tsx',
      PATH: '/display?component=DMLBNPD007',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-08-01',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'D_ML_VDO_007_1',
      전시타입: '1열 전체 숏폼',
      FILE: '/widgets/display/DMLVDO007_1.tsx',
      PATH: '/display?component=DMLVDO007_1',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-08-01',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'D_ML_BN_004',
      전시타입: '세로 중앙정렬형 전면 메인배너',
      FILE: '/widgets/display/DMLBN004.tsx',
      PATH: '/display?component=DMLBN004',
      작업자: '최수연',
      상태: 'removed',
      완료일: '2025-08-01',
      최종수정일: null,
      비고: null,
    },
    {
      '모듈 ID': 'ML_B_CT_001',
      전시타입: '텍스트 카테고리 배너',
      FILE: '/widgets/display/MLBCT001.tsx',
      PATH: '/display?component=MLBCT001',
      작업자: '최수연',
      상태: 'completed',
      완료일: '2025-08-12',
      최종수정일: null,
      비고: null,
    },
  ],
} as const;

export default display;
