const member = {
  pages: [
    {
      '1Depth': '회원가입',
      '2Depth': '회원가입 안내',
      '3Depth': '해외 IP',
      '4Depth': '',
      FILE: '/auth/join/unified/JoinGuide.tsx',
      PATH: '/join/unified/guide?status=status1',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '국내 IP',
      '4Depth': '',
      FILE: '/auth/join/unified/JoinGuide.tsx',
      PATH: '/join/unified/guide?status=status2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 통합회원 전환 안내 (L)',
      '4Depth': '',
      FILE: '/auth/info/UnifiedMemberInfoDialog.tsx',
      PATH: '/join/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '통합회원 본인인증',
      '4Depth': '',
      FILE: '/auth/join/unified/Join.tsx',
      PATH: '/join/unified',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '통합회원 기가입자 안내',
      '4Depth': 'NCP가입',
      FILE: '/auth/join/unified/JoinedUserGuide.tsx',
      PATH: '/join/unified/joined?status=status1',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'H.Point 고객상태 사용불가일경우',
      FILE: '/auth/join/unified/JoinedUserGuide.tsx',
      PATH: '/join/unified/joined?status=status2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'H.Point 가입실패안내',
      FILE: '/auth/join/unified/JoinedUserGuide.tsx',
      PATH: '/join/unified/joined?status=status3',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'H.Point 가입실패안내_글로벌',
      FILE: '/auth/join/unified/JoinedUserGuide.tsx',
      PATH: '/join/unified/joined?status=status4',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'H.Point 가입실패안내_시스템점검',
      FILE: '/auth/join/unified/JoinedUserGuide.tsx',
      PATH: '/join/unified/joined?status=status5',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '약관 동의',
      '4Depth': '신규회원가입',
      FILE: '/auth/join/unified/JoinStep1.tsx',
      PATH: '/join/unified/agree?status=status1',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '선가입',
      FILE: '/auth/join/unified/JoinStep1.tsx',
      PATH: '/join/unified/agree?status=status2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '투홈 일반회원 가입시',
      FILE: '/auth/join/unified/JoinStep1.tsx',
      PATH: '/join/unified/agree?status=status3',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '현대백화점 통합회원일 경우',
      FILE: '/auth/join/unified/JoinStep1.tsx',
      PATH: '/join/unified/agree?status=status4',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'e현대 약관 미동의한 회원',
      FILE: '/auth/join/unified/JoinStep1.tsx',
      PATH: '/join/unified/agree?status=status5',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '가입정보 입력',
      '4Depth': '',
      FILE: '/auth/join/unified/JoinStep2.tsx',
      PATH: '/join/unified/register',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '★ 에러 안내문구',
      FILE: '/auth/join/unified/components/JoinStep2Error.tsx',
      PATH: '/join/unified/register?view=error',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-23',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '회원가입 완료',
      '4Depth': '',
      FILE: '/auth/join/unified/JoinComplete.tsx',
      PATH: '/join/unified/complete?status=status1',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '/auth/join/unified/JoinComplete.tsx',
      PATH: '/join/unified/complete?status=status2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '통합가입실패',
      FILE: '/auth/join/unified/JoinComplete.tsx',
      PATH: '/join/unified/complete?status=status3',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'H Point 단독가입',
      FILE: '/auth/join/unified/JoinComplete.tsx',
      PATH: '/join/unified/complete?status=status4',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': 'SNS 계정 인증',
      '4Depth': '',
      FILE: '/auth/join/unified/JoinSnsVerify.tsx',
      PATH: '/join/unified/verify',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '일반회원 가입',
      '3Depth': '일반회원 가입 안내',
      '4Depth': '',
      FILE: '/auth/join/normal/Join.tsx',
      PATH: '/join/normal',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '이메일 인증',
      FILE: '/auth/join/normal/Join.tsx',
      PATH: '/join/normal/verify',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '약관 동의',
      '4Depth': '',
      FILE: '/auth/join/normal/JoinStep1.tsx',
      PATH: '/join/normal/agree',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '가입정보 입력',
      '4Depth': '이메일 인증',
      FILE: '/auth/join/normal/JoinStep2.tsx',
      PATH: '/join/normal/register?method=email',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'SNS게정 인증',
      FILE: '/auth/join/normal/JoinStep2.tsx',
      PATH: '/join/normal/register?method=sns',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '회원가입 완료',
      '4Depth': '',
      FILE: '/auth/join/normal/JoinComplete.tsx',
      PATH: '/join/normal/complete',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'BIZ회원 가입',
      '3Depth': '휴대폰 인증',
      '4Depth': '',
      FILE: '/auth/join/biz/Join.tsx',
      PATH: '/join/biz',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '약관 동의',
      '4Depth': '',
      FILE: '/auth/join/biz/JoinStep1.tsx',
      PATH: '/join/biz/agree?status=biz',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '가입정보 입력',
      '4Depth': '',
      FILE: '/auth/join/biz/JoinStep2.tsx',
      PATH: '/join/biz/register?status=biz',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '★ 에러 안내문구',
      FILE: '/auth/join/biz/components/BizJoinStep2Error.tsx',
      PATH: '/join/biz/register?status=biz&view=error',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-23',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '회원가입 완료',
      '4Depth': '',
      FILE: '/auth/join/biz/JoinComplete.tsx',
      PATH: '/join/biz/complete',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'BIZ회원 가입 (url)',
      '3Depth': '휴대폰 인증',
      '4Depth': '',
      FILE: '/auth/join/biz/Join.tsx',
      PATH: '/join/biz',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '약관 동의',
      '4Depth': '',
      FILE: '/auth/join/biz/JoinStep1.tsx',
      PATH: '/join/biz/agree?status=bizUrl',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '가입정보 입력',
      '4Depth': '',
      FILE: '/auth/join/biz/JoinStep2.tsx',
      PATH: '/join/biz/register?status=bizUrl',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '회원가입 완료',
      '4Depth': '',
      FILE: '/auth/join/biz/JoinComplete.tsx',
      PATH: '/join/biz/complete',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '로그인',
      '2Depth': '통합회원 로그인',
      '3Depth': '',
      '4Depth': '',
      FILE: '/auth/login/components/UnifiedLoginForm.tsx',
      PATH: '/login',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '★ 에러 안내문구',
      '4Depth': '',
      FILE: '/auth/login/components/UnifiedLoginForm.tsx',
      PATH: '/login?view=error',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-23',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ QR 스캔 (L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/auth/qr/QrCodeScanDialog.tsx',
      PATH: '/login/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '2025-08-11',
      비고: '디자인변경 수정',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ QR 스캔 모바일 (L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/auth/qr/QrCodeScanMobileDialog.tsx',
      PATH: '/login/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '2025-08-11',
      비고: '디자인변경 수정',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '약관동의',
      '4Depth': '선가입자  NCP 약관 동의',
      FILE: '/auth/login/components/Agreement.tsx',
      PATH: '/login/agree',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '최초 로그인시 NCP 약관 동의 (L)',
      FILE: '/policy/TermsAgreeDrawer',
      PATH: '/login/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '아이디/비밀번호 찾기',
      '4Depth': '',
      FILE: '/auth/find/unified/UnifiedFindIdPw.tsx',
      PATH: '/find',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '아이디 찾기 결과',
      '4Depth': '성공',
      FILE: '/auth/find/unified/UnifiedFindIdResult.tsx',
      PATH: '/find/id/result?status=success',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '실패',
      FILE: '/auth/find/unified/UnifiedFindIdResult.tsx',
      PATH: '/find/id/result?status=fail',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '비밀번호 재설정',
      '4Depth': '',
      FILE: '	/auth/find/FindPwReset.tsx',
      PATH: '/find/password/reset',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '신규 비밀번호 입력',
      FILE: '	/auth/find/FindPwChange.tsx',
      PATH: '/find/password/change',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '일반회원 로그인',
      '3Depth': '해외 IP',
      '4Depth': '',
      FILE: '/auth/login/components/NormalLoginForm.tsx',
      PATH: '/login?userType=normal&status=status1',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '국내 IP',
      '4Depth': '',
      FILE: '/auth/login/components/NormalLoginForm.tsx',
      PATH: '/login?userType=normal&status=status2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '통합회원 전환하기',
      '4Depth': '',
      FILE: '/auth/unify/MemberConversion.tsx',
      PATH: '/unify',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '본인인증',
      FILE: '/auth/verify/UserVerify.tsx',
      PATH: '/verify',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '아이디/비밀번호 찾기',
      '4Depth': '',
      FILE: '/auth/find/normal/NormalFindIdPw.tsx',
      PATH: '/find?userType=normal',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '아이디 찾기 결과',
      '4Depth': '',
      FILE: '/auth/find/normal/NormalFindIdResult.tsx',
      PATH: '/find/id/result?userType=normal',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '2025-08-13',
      비고: '단건 화면확인',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '여러 개',
      FILE: '/auth/find/normal/NormalFindIdResult.tsx',
      PATH: '/find/id/result?userType=normal&case2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-08-13',
      최종수정일: '2025-08-13',
      비고: '다건 화면확인',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '전체 아이디 찾기',
      '4Depth': '이메일인증',
      FILE: '/auth/find/FindIdEmailVerify.tsx',
      PATH: '/find/id/verify/email',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '휴대폰인증',
      FILE: '/auth/find/FindIdPhoneVerify.tsx',
      PATH: '/find/id/verify/phone',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '전체 아이디 찾기 결과',
      '4Depth': '',
      FILE: '/auth/find/normal/NormalFindIdComplete.tsx',
      PATH: '/find/id/complete',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '비밀번호 찾기',
      '4Depth': '이메일인증',
      FILE: '/auth/find/FindPwEmailVerify.tsx',
      PATH: '/find/password/verify/email',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '휴대폰인증',
      FILE: '/auth/find/FindPwPhoneVerify.tsx',
      PATH: '/find/password/verify/phone',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '신규 비밀번호 입력',
      FILE: '/auth/find/FindPwChange.tsx',
      PATH: '/find/password/change?userType=normal',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'BIZ회원 로그인',
      '3Depth': '아이디/비밀번호 찾기',
      '4Depth': '',
      FILE: '/auth/find/biz/BizFindIdPw.tsx',
      PATH: '/find?userType=biz',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '아이디 찾기 결과',
      '4Depth': '',
      FILE: '/auth/find/biz/BizFindIdResult.tsx',
      PATH: '/find/id/result?userType=biz',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '전체 아이디 찾기 결과',
      '4Depth': '',
      FILE: '/auth/find/biz/BizFindIdComplete.tsx',
      PATH: '/find/id/complete?userType=biz',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '비밀번호 찾기',
      '4Depth': '휴대폰인증',
      FILE: '/auth/find/FindPwPhoneVerify.tsx',
      PATH: '/find/password/verify/phone',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'BIZ회원 약관동의',
      FILE: '	/auth/join/biz/JoinStep1.tsx',
      PATH: '	/join/biz/agree?status=bizUrl',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '신규 비밀번호 입력',
      FILE: '/auth/find/FindPwChange.tsx',
      PATH: '/find/password/change',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '장기 미변경 비밀번호 변경 안내 (L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/auth/login/etc/Page.tsx',
      PATH: '/login/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-23',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '휴면 해제 안내 (L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/auth/verify/AuthCheckDialog.tsx',
      PATH: '/login/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '전환 가입 안내 팝업 (L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/auth/info/UnifiedGuideDialog.tsx',
      PATH: '/login/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '전환 가입 약관동의',
      '3Depth': '',
      '4Depth': '',
      FILE: '/auth/unify/ConversionAgreement.tsx',
      PATH: '/unify/agree',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-06-17',
      최종수정일: '',
      비고: '',
    },
  ],
} as const;

export default member;
