const o4o = {
  pages: [
    {
      '1Depth': '테이블 오더',
      '2Depth': '앱 설치 안내',
      '3Depth': '',
      '4Depth': '',
      FILE: '/o4o/torder/AppInstallGuide.tsx',
      PATH: '/o4o/torder/app',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'QR스캔',
      '3Depth': '',
      '4Depth': '',
      FILE: '/o4o/torder/TorderQrCodeScanDialog.tsx',
      PATH: '/o4o/torder/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 카메라 설정(D)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/etc/CameraSettingsDrawer.tsx',
      PATH: '/o4o/torder/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '매장 리스트',
      '3Depth': '[case1. 압구정 본점]',
      '4Depth': '로그인',
      FILE: '/o4o/torder/TorderStoreList.tsx',
      PATH: '/o4o/torder/stores?status=apgujeong',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '미로그인',
      FILE: '/o4o/torder/TorderStoreList.tsx',
      PATH: '/o4o/torder/stores?status=apgujeong&guest=true',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[case2. 압구정 본점, 대전 아울렛점 제외 지점]',
      '4Depth': '로그인',
      FILE: '/o4o/torder/TorderStoreList.tsx',
      PATH: '/o4o/torder/stores?status=general',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '미로그인',
      FILE: '/o4o/torder/TorderStoreList.tsx',
      PATH: '/o4o/torder/stores?status=general&guest=true',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[case3. 대전아울렛점(로봇 딜리버리)]',
      '4Depth': '로그인',
      FILE: '/o4o/torder/TorderStoreList.tsx',
      PATH: '/o4o/torder/stores?status=daejeonOutlet',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '미로그인',
      FILE: '/o4o/torder/TorderStoreList.tsx',
      PATH: '/o4o/torder/stores?status=daejeonOutlet&guest=true',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[case4. 매장 목록 없음]',
      '4Depth': '',
      FILE: '/o4o/torder/TorderStoreList.tsx',
      PATH: '/o4o/torder/stores?status=empty',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '매장 상세',
      '4Depth': '로그인',
      FILE: '/o4o/torder/TorderStoreDetail.tsx',
      PATH: '/o4o/torder/detail/store',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 매장정보(L)',
      '4Depth': '',
      FILE: '/o4o/torder/TorderStoreDetailDialog.tsx',
      PATH: '/o4o/torder/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 이미지 크게보기(L)',
      '4Depth': '',
      FILE: '/widgets/o4o/TorderImageViewerDialog.tsx',
      PATH: '/o4o/torder/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '미로그인',
      FILE: '/o4o/torder/TorderStoreDetail.tsx',
      PATH: '/o4o/torder/detail/store?guest=true',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '지연 Toast',
      FILE: '/o4o/torder/TorderStoreDetail.tsx',
      PATH: '/o4o/torder/detail/store?delay=true',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '메뉴 상세',
      '4Depth': '',
      FILE: '/o4o/torder/TorderMenuDetail.tsx',
      PATH: '/o4o/torder/detail/menu',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '이미지 없는 경우',
      FILE: '/o4o/torder/TorderMenuDetail.tsx',
      PATH: '/o4o/torder/detail/menu?status=noImage',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '주문 불가',
      FILE: '/o4o/torder/TorderMenuDetail.tsx',
      PATH: '/o4o/torder/detail/menu?status=unavailable',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '장바구니',
      '3Depth': '[case1. 압구정 본점]',
      '4Depth': '',
      FILE: '/o4o/torder/TorderCart.tsx',
      PATH: '/o4o/torder/cart?status=apgujeong',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '테이블 번호 없는 경우',
      FILE: '/o4o/torder/TorderCart.tsx',
      PATH: '/o4o/torder/cart?status=apgujeong&qr=true',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[case2. 압구정 본점, 대전 아울렛점 제외 지점]',
      '4Depth': '',
      FILE: '/o4o/torder/TorderCart.tsx',
      PATH: '/o4o/torder/cart?status=general',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[case3. 대전 아울렛점]',
      '4Depth': '',
      FILE: '/o4o/torder/TorderCart.tsx',
      PATH: '/o4o/torder/cart?status=daejeonOutlet',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '픽업존 위치 없는 경우',
      FILE: '/o4o/torder/TorderCart.tsx',
      PATH: '/o4o/torder/cart?status=daejeonOutlet&qr=true',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[case4. 비회원]',
      '4Depth': '',
      FILE: '/o4o/torder/TorderCart.tsx',
      PATH: '/o4o/torder/cart?status=apgujeong&guest=true',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[case5. 데이터 없는 경우]',
      '4Depth': '',
      FILE: '/o4o/torder/TorderCart.tsx',
      PATH: '/o4o/torder/cart?status=empty',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '주문하기',
      '3Depth': '[case1. 회원]',
      '4Depth': '',
      FILE: '/o4o/torder/TorderOrder.tsx',
      PATH: '/o4o/torder/order',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[case2. 비회원]',
      '4Depth': '',
      FILE: '/o4o/torder/TorderOrder.tsx',
      PATH: '/o4o/torder/order?guest=true',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '주문완료',
      '3Depth': '[case1. 압구정 본점]',
      '4Depth': '',
      FILE: '/o4o/torder/TorderComplete.tsx',
      PATH: '/o4o/torder/complete?status=apgujeong',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[case2. 압구정 본점, 대전 아울렛점 제외 지점]',
      '4Depth': '',
      FILE: '/o4o/torder/TorderComplete.tsx',
      PATH: '/o4o/torder/complete?status=general',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[case3. 대전 아울렛점]',
      '4Depth': '',
      FILE: '/o4o/torder/TorderComplete.tsx',
      PATH: '/o4o/torder/complete?status=daejeonOutlet',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-08-07',
      최종수정일: '',
      비고: '',
    },
  ],
} as const;

export default o4o;
