const order = {
  pages: [
    // 장바구니(일반)
    {
      '1Depth': '장바구니',
      '2Depth': '일반',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/cart/CartForm.tsx',
      PATH: '/shop/cart',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-20',
      최종수정일: '2025-07-22',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 클럽혜택안내(D)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/cart/BenefitDrawer.tsx',
      PATH: '/shop/cart/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-20',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 옵션변경(D)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/cart/OptionChangeDrawer.tsx',
      PATH: '/shop/cart/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-20',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 배송비 절약 상품 팝업(L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/cart/SaverDialog.tsx',
      PATH: '/shop/cart/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-20',
      최종수정일: '2025-07-14',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '빈 장바구니',
      '4Depth': '',
      FILE: '/shop/cart/empty/Empty.tsx',
      PATH: '/shop/cart/empty',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-20',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽혜택안내(클럽 패션)',
      '4Depth': '',
      FILE: '/shop/cart/benefit/Benefit.tsx',
      PATH: '/shop/cart/benefit',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-20',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '여러곳으로 배송지 설정',
      '4Depth': '',
      FILE: '/shop/cart/address/MultiDelivery.tsx',
      PATH: '/shop/cart/address',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-20',
      최종수정일: '2025-07-14',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '엑셀업로드',
      FILE: '/shop/cart/upload/FileUpload.tsx',
      PATH: '/shop/cart/upload',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-20',
      최종수정일: '2025-07-14',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '새벽/당일배송 정보 입력',
      '4Depth': '',
      FILE: '/shop/cart/express/ExpressDeliveryForm.tsx',
      PATH: '/shop/cart/express',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-20',
      최종수정일: '2025-07-14',
      비고: '',
    },
    // 장바구니(선물)
    {
      '1Depth': '',
      '2Depth': '선물',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/cart/CartPresentForm.tsx',
      PATH: '/shop/cart/present',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-11',
      최종수정일: '2025-07-22',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 선물픽 / 바로선물 안내 팝업(L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/cart/present/GiftPickGuideDialog.tsx',
      PATH: '/shop/cart/present/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-11',
      최종수정일: '2025-07-16',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '여러명에게 선물',
      '4Depth': '',
      FILE: '/shop/cart/CartPresentMultiForm.tsx',
      PATH: '/shop/cart/present/multi',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-11',
      최종수정일: '2025-07-23',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 연락처로 추가(L)',
      '4Depth': '',
      FILE: '/shop/cart/present/ImportContactsDialog.tsx',
      PATH: '/shop/cart/present/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-11',
      최종수정일: '2025-07-15',
      비고: '',
    },
    // 주문서
    {
      '1Depth': '주문서',
      '2Depth': '일반',
      '3Depth': '배송지 하나',
      '4Depth': '(국외)',
      '5Depth': '',
      FILE: '/shop/order/normal/OrderForm.tsx',
      PATH: '/shop/order/normal?status=status1',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '2025-07-23',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '(국내)',
      '5Depth': '',
      FILE: '/shop/order/normal/OrderForm.tsx',
      PATH: '/shop/order/normal?status=status2',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 쿠폰 변경 (L)',
      FILE: '/widgets/order/CouponChangeDialog.tsx',
      PATH: '/shop/order/normal/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '2025-08-04',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 통 이미지 (L)',
      FILE: '/widgets/payment/NoticeDialog.tsx',
      PATH: '/shop/order/normal/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 배송 가능 지역 확인 (L)',
      FILE: '/widgets/order/DeliveryZoneDialog.tsx',
      PATH: '/shop/order/normal/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 픽업 장소 (L)',
      FILE: '/widgets/order/LocationDialog.tsx',
      PATH: '/shop/order/normal/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 스토어픽 선물하기 (D)',
      FILE: '/widgets/order/StorepickGiftDrawer.tsx',
      PATH: '/shop/order/normal/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 개인통관고유부호 조회 (D)',
      FILE: '/widgets/order/AgreementDrawer.tsx',
      PATH: '/shop/order/normal/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 개인통관고유부호 - 개인정보 수집.이용 동의 (L)',
      FILE: '/widgets/agreement/PrivacyDialog.tsx',
      PATH: '/shop/order/normal/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 개인통관고유부호 - 개인정보 제3자 제공 동의 (관세청) (L)',
      FILE: '/widgets/agreement/PrivacyDialog.tsx',
      PATH: '/shop/order/normal/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 개인통관고유부호 조회 결과 (L)',
      FILE: '/widgets/order/CodeResultDialog.tsx',
      PATH: '/shop/order/normal/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 등록할 결제수단 선택 (D)',
      FILE: '/widgets/payment/MethodSelectDrawer.tsx',
      PATH: '/shop/order/normal/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 에스크로 (L)',
      FILE: '/widgets/payment/EscrowInfoDialog.tsx',
      PATH: '/shop/order/normal/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 지류 상품권 사용방법 (L)',
      FILE: '/widgets/payment/VoucherInfoDialog.tsx',
      PATH: '/shop/order/normal/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 주문서 약관 - 전자금융거래 이용약관 동의 (L)',
      FILE: '/widgets/agreement/PrivacyDialog.tsx',
      PATH: '/shop/order/normal/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 주문서 약관 - 개인정보 수집 및 이용 동의 (L)',
      FILE: '/widgets/agreement/PrivacyDialog.tsx',
      PATH: '/shop/order/normal/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 주문서 약관 - 개인정보 제3자 제공/위탁 동의 (L)',
      FILE: '/widgets/agreement/PrivacyDialog.tsx',
      PATH: '/shop/order/normal/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 주문서 약관 - 개별판매자 개인정보 제공안내 (L)',
      FILE: '/widgets/agreement/PrivacyDialog.tsx',
      PATH: '/shop/order/normal/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 간편주문서 (D)',
      FILE: '/widgets/order/QuickOrderDrawer.tsx',
      PATH: '/shop/order/normal/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 최적할인 적용 (L)',
      FILE: '/widgets/order/BestDiscountDialog.tsx',
      PATH: '/shop/order/normal/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '배송지 멀티',
      '4Depth': '',
      '5Depth': '',
      FILE: '/shop/order/normal/OrderMultiForm.tsx',
      PATH: '/shop/order/normal/multi',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '2025-07-23',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': 'e쿠폰',
      '4Depth': '',
      '5Depth': '',
      FILE: '/shop/order/normal/OrderCouponForm.tsx',
      PATH: '/shop/order/normal/ecoupon',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '2025-07-23',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '상품 상세',
      '3Depth': '',
      '4Depth': '',
      '5Depth': '',
      FILE: '/shop/order/normal/detail/ProductDetail.tsx',
      PATH: '/shop/order/normal/detail',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '선물',
      '3Depth': '1명에게',
      '4Depth': '',
      '5Depth': '',
      FILE: '/shop/order/present/PresentForm.tsx',
      PATH: '/shop/order/present',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '2025-07-23',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '선물픽',
      '4Depth': '',
      '5Depth': '',
      FILE: '/shop/order/present/PresentPickForm.tsx',
      PATH: '/shop/order/present/pick',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '2025-07-23',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '선물멀티발송',
      '4Depth': '',
      '5Depth': '',
      FILE: '/shop/order/present/PresentMultiForm.tsx',
      PATH: '/shop/order/present/multi',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '2025-07-23',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '상담 신청서 작성',
      '3Depth': '',
      '4Depth': '',
      '5Depth': '',
      FILE: '/shop/order/request/RequestForm.tsx',
      PATH: '/shop/order/request',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '사은품 신청',
      '3Depth': '',
      '4Depth': '',
      '5Depth': '',
      FILE: '/shop/order/request/GiftRequestForm.tsx',
      PATH: '/shop/order/gift',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-06-30',
      최종수정일: '',
      비고: '',
    },
    // 주문완료
    {
      '1Depth': '주문완료',
      '2Depth': '일반',
      '3Depth': '1곳으로 배송',
      '4Depth': '',
      '5Depth': '',
      FILE: '/shop/order/complete/CompleteForm.tsx',
      PATH: '/shop/order/complete?status=single',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '멀티 배송',
      '4Depth': '',
      '5Depth': '',
      FILE: '/shop/order/complete/CompleteForm.tsx',
      PATH: '/shop/order/complete?status=multi',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '선물',
      '3Depth': '카카오톡으로 보내기',
      '4Depth': '',
      '5Depth': '',
      FILE: '/shop/order/complete/CompletePresentForm.tsx',
      PATH: '/shop/order/complete/present?status=kakao',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '2025-07-11',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '문자로 보내기',
      '4Depth': '',
      '5Depth': '',
      FILE: '/shop/order/complete/CompletePresentForm.tsx',
      PATH: '/shop/order/complete/present?status=lms',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '선물픽',
      '4Depth': '카카오톡으로 보내기',
      '5Depth': '',
      FILE: '/shop/order/complete/CompletePresentForm.tsx',
      PATH: '/shop/order/complete/present?status=pickKakao',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '2025-07-11',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '문자로 보내기',
      '5Depth': '',
      FILE: '/shop/order/complete/CompletePresentForm.tsx',
      PATH: '/shop/order/complete/present?status=pickLms',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '2025-07-11',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '멀티 배송',
      '4Depth': '',
      '5Depth': '',
      FILE: '/shop/order/complete/CompletePresentForm.tsx',
      PATH: '/shop/order/complete/present?status=multi',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '2025-07-11',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'e쿠폰/이용권',
      '3Depth': '',
      '4Depth': '',
      '5Depth': '',
      FILE: '/shop/order/complete/CompleteSpecialForm.tsx',
      PATH: '/shop/order/complete/special?status=coupon',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '문화센터',
      '3Depth': '',
      '4Depth': '',
      '5Depth': '',
      FILE: '/shop/order/complete/CompleteSpecialForm.tsx',
      PATH: '/shop/order/complete/special?status=center',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '서비스 예약, 여행(ASP), 렌탈 상품',
      '3Depth': '',
      '4Depth': '',
      '5Depth': '',
      FILE: '/shop/order/complete/CompleteApplyForm.tsx',
      PATH: '/shop/order/complete/apply',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '방문 쿠폰',
      '3Depth': '',
      '4Depth': '',
      '5Depth': '',
      FILE: '/shop/order/complete/CompleteVisitForm.tsx',
      PATH: '/shop/order/complete/visit?status=coupon',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '방문 예약',
      '3Depth': '',
      '4Depth': '',
      '5Depth': '',
      FILE: '/shop/order/complete/CompleteVisitForm.tsx',
      PATH: '/shop/order/complete/visit?status=apply',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '사은품 신청',
      '3Depth': '',
      '4Depth': '',
      '5Depth': '',
      FILE: '/shop/order/complete/CompleteGiftForm.tsx',
      PATH: '/shop/order/complete/gift',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-04',
      최종수정일: '',
      비고: '',
    },
  ],
} as const;

export default order;
