const shop = {
  pages: [
    // 카테고리
    {
      '1Depth': '카테고리',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '/category/CategoryMenu.tsx',
      PATH: '/category',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-07-21',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '대카테고리',
      '3Depth': '',
      '4Depth': '',
      FILE: '/category/CategoryDepth1.tsx',
      PATH: '/category/depth1',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-07-21',
      최종수정일: '',
      비고: '필터영역 TBD',
    },
    {
      '1Depth': '',
      '2Depth': '중소카테고리',
      '3Depth': '',
      '4Depth': '',
      FILE: '/category/CategoryDepth2.tsx',
      PATH: '/category/depth2',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-07-21',
      최종수정일: '',
      비고: '필터영역 TBD',
    },
    // 샵메인
    {
      '1Depth': '샵메인',
      '2Depth': 'SHOP(T)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/main/ShopMain.tsx',
      PATH: '/shop/main',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-07-17',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '쇼룸 모아보기',
      '4Depth': '',
      FILE: '/shop/showroom/Showroom.tsx',
      PATH: '/shop/showroom',
      작업자: '하윤정',
      상태: 'completed',
      완료일: '2025-07-08',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'BRAND(T)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/main/BrandMain.tsx',
      PATH: '/shop/brand',
      작업자: '하윤정',
      상태: 'progress',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    // 브랜드관
    {
      '1Depth': '브랜드관',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '/brand/BrandStore.tsx',
      PATH: '/brand',
      작업자: '하윤정',
      상태: 'progress',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '상품 목록 (full case)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/brand/BrandShop.tsx',
      PATH: '/brand/shop',
      작업자: '하윤정',
      상태: 'progress',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    // 상품 상세 - 일반
    {
      '1Depth': '상품 상세',
      '2Depth': '공통',
      '3Depth': '판매중',
      '4Depth': '',
      FILE: '/shop/detail/GeneralDetail.tsx',
      PATH: '/shop/detail',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: 'RSVP,계약금/위약금/잔금,희망일(설치)배송,교차할인 포함',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 판매 상태',
      '3Depth': '품절',
      '4Depth': '',
      FILE: '/widget/detail/cta/ProdStateCTA.tsx',
      PATH: '/shop/detail?prodState=soldout',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '일시중단',
      '4Depth': '',
      FILE: '/widget/detail/cta/ProdStateCTA.tsx',
      PATH: '/shop/detail?prodState=paused',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '일시품절',
      '4Depth': '',
      FILE: '/widget/detail/cta/ProdStateCTA.tsx',
      PATH: '/shop/detail?prodState=outOfStock',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '일시품절',
      '4Depth': '재입고 알림',
      FILE: '/widget/detail/cta/AlramDialog.tsx',
      PATH: '/shop/detail?prodState=outOfStock',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '선공개',
      '4Depth': '',
      FILE: '/widget/detail/cta/ProdStateCTA.tsx',
      PATH: '/shop/detail?prodState=preRelease',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '공개 알림 신청',
      FILE: '/widget/detail/cta/AlramDialog.tsx',
      PATH: '/shop/detail?prodState=preRelease',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '에러',
      '4Depth': '일시정지',
      FILE: '/shop/detail/ErrorDetail.tsx',
      PATH: '/shop/detail/preparing',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '에러',
      '4Depth': '접근불가',
      FILE: '/shop/detail/ErrorDetail.tsx',
      PATH: '/shop/detail/error',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 탑 정보 영역',
      '3Depth': '가격 정보 노출 CASE',
      '4Depth': '',
      FILE: '/widgets/detail/DetailPrice.tsx',
      PATH: '/shop/detail/normal?component=DetailPrice',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '중개 상품 CASE',
      '4Depth': '',
      FILE: '/widgets/detail/DetailTop.tsx',
      PATH: '/shop/detail/normal?component=Brockerage',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '교차 할인 노출 CASE',
      '4Depth': '',
      FILE: '/widgets/detail/DetailTop.tsx',
      PATH: '/shop/detail/normal?component=CrossDiscount',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '혜택 계산기 (로그인 O)',
      '4Depth': '',
      FILE: '/widgets/detail/DetailTop.tsx',
      PATH: '/shop/detail?isLogin=true',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '혜택 계산기 (멤버 O)',
      '4Depth': '',
      FILE: '/widgets/detail/DetailTop.tsx',
      PATH: '/shop/detail?isLogin=true&isMember=true',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '식품상품(구 투홈)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/detail/GeneralDetail.tsx',
      PATH: '/shop/detail?prodCategory=food',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '스토어픽',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/detail/GeneralDetail.tsx',
      PATH: '/shop/detail?prodType=storepick',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '방문픽업',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/detail/GeneralDetail.tsx',
      PATH: '/shop/detail?prodDetailType=visitPick',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 방문픽업 선택 팝업',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/cta/drawer/SelectDateSection.tsx',
      PATH: '/shop/detail?prodDetailType=visitPick',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '스페셜브랜드',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/detail/GeneralDetail.tsx',
      PATH: '/shop/detail?prodDetailType=specialBrand',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '쇼룸',
      '3Depth': '1:1채팅 N',
      '4Depth': '',
      FILE: '/widgets/detail/cta/ShowroomCTA.tsx',
      PATH: '/shop/detail?prodType=showroom',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '1:1채팅 Y',
      '4Depth': '',
      FILE: '/widgets/detail/cta/ShowroomCTA.tsx',
      PATH: '/shop/detail?prodType=showroom&useChat=true',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '상담 후 결제',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/detail/GeneralDetail.tsx',
      PATH: '/shop/detail?prodType=serviceReserve',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '라이브',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/detail/GeneralDetail.tsx',
      PATH: '/shop/detail?prodType=live',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '예약 판매',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/detail/GeneralDetail.tsx',
      PATH: '/shop/detail?prodDetailType=preOrder',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 예약 판매 선택 팝업',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/cta/drawer/SelectDateSection.tsx',
      PATH: '/shop/detail?prodDetailType=preOrder',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '옥션',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/detail/GeneralDetail.tsx',
      PATH: '/shop/detail?prodType=auction',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '옥션 상단 CASE',
      '4Depth': '',
      FILE: '/widget/detail/DetailPriceAuction.tsx',
      PATH: '/shop/detail/normal?component=AuctionTop',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '옥션 CTA CASE',
      '4Depth': '',
      FILE: '/widget/detail/cta/AuctionCTA.tsx',
      PATH: '/shop/detail/normal?component=AuctionCta',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '래플',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/detail/GeneralDetail.tsx',
      PATH: '/shop/detail?prodType=raffle',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '래플 상단 CASE',
      '4Depth': '',
      FILE: '/widget/detail/DetailPriceRaffle.tsx',
      PATH: '/shop/detail/normal?component=RaffleTop',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '래플 CTA CASE',
      '4Depth': '',
      FILE: '/widget/detail/cta/RaffleCTA.tsx',
      PATH: '/shop/detail/normal?component=RaffleCta',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '햄퍼',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/detail/GeneralDetail.tsx',
      PATH: '/shop/detail?prodType=hamper',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '딜',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/detail/GeneralDetail.tsx',
      PATH: '/shop/detail?prodType=deal',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 상품 자세히보기 팝업',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/DealDetailDialog.tsx',
      PATH: '/shop/detail?prodType=deal',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '사은품',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/detail/GeneralDetail.tsx',
      PATH: '/shop/detail?prodType=freegift',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '명절배송',
      '3Depth': '',
      '4Depth': '',
      FILE: '/shop/detail/GeneralDetail.tsx',
      PATH: '/shop/detail?prodDetailType=holidayOnly',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 명절배송 바코드 팝업',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/detail/BarcodeDialog.tsx',
      PATH: '/shop/detail?prodDetailType=holidayOnly',
      작업자: '김효정',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    // 상품 상세 - 정기 구독
    {
      '1Depth': '',
      '2Depth': '정기 구독',
      '3Depth': '첫 구독 +  옵션 선택 완료',
      '4Depth': '',
      FILE: '/shop/detail/GeneralDetail.tsx',
      PATH: '/shop/detail?prodDetailType=subscription',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '회차별 구성 상품 보기 노출',
      '4Depth': '',
      FILE: '/shop/detail/GeneralDetail.tsx',
      PATH: '/shop/detail?prodDetailType=subscription&hasRounds=true',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '추가 구독 + 옵션 선택 완료',
      '4Depth': '',
      FILE: '/shop/detail/GeneralDetail.tsx',
      PATH: '/shop/detail?prodDetailType=subscription&isSubscribed=true',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '판매종료',
      '4Depth': '',
      FILE: '/shop/detail/GeneralDetail.tsx',
      PATH: '/shop/detail?prodDetailType=subscription&prodState=soldout',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '일시품절',
      '4Depth': '',
      FILE: '/shop/detail/GeneralDetail.tsx',
      PATH: '/shop/detail?prodDetailType=subscription&prodState=outOfStock',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 정기구독 설정 (L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/coupon/SubscriptionSettingsDialog.tsx',
      PATH: '/shop/detail/subscription/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 회차별 구성상품 보기 (L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/coupon/SubscriptionRoundProductDialog.tsx',
      PATH: '/shop/detail/subscription/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '⤷ 상품 구매 정보 안내 (L)',
      '3Depth': '',
      '4Depth': '',
      FILE: '/widgets/coupon/ProductPurchaseDialog.tsx',
      PATH: '/shop/detail/subscription/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '신청서',
      '4Depth': '',
      FILE: '/shop/detail/subscription/SubscriptionForm.tsx',
      PATH: '/shop/detail/subscription/form',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '데이터 없는 경우',
      FILE: '/shop/detail/subscription/SubscriptionForm.tsx',
      PATH: '/shop/detail/subscription/form?status=empty',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '신청 완료',
      FILE: '/shop/detail/subscription/SubscriptionForm.tsx',
      PATH: '/shop/detail/subscription/form?status=complete',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-29',
      최종수정일: '',
      비고: '',
    },
  ],
} as const;

export default shop;
