const mypage = {
  pages: [
    {
      '1Depth': '팝업모음집',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '주문 케이스',
      '2Depth': 'Full case',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/case?type=myOrder',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '플래그 케이스',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/case?type=flag',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '버튼 케이스',
      '3Depth': '공통',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/btns?type=common',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '스토어픽',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/btns?type=storepick',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '선물하기',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/btns?type=gift',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '방문픽업',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/btns?type=pickup',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '체험단/0원상품',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/btns?type=experience',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '기타',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/btns?type=etc',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '취소 가능 케이스',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/btns?type=cancelable',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '문화센터 예외',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/btns?type=culture',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },

    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: '',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '주문/배송',
      '2Depth': '목록',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/list',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '결과없음',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/list?nodata',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '영수증',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/receipt',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: '',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '상세',
      '3Depth': '일반',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/normal',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '일반 - 멀티',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/normal/multi',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '스토어픽',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/storepick',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '선물하기',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/gift',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '선물하기 - 멀티',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/gift/multi',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '역직구_EMS',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/global/export',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '직구',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/global/import',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '렌탈',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/rental',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '명절배송',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/holiday',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '체험단',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/experience',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '문화센터',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/culture',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '방문픽업',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/visit',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '사은품 - 0원상품',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/purchasegift',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[컴퍼넌트 케이스]',
      '4Depth': '결제수단 & 승인내역',
      FILE: '',
      PATH: '/mypage/order/case?type=paymentApproval',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '결제정보',
      FILE: '',
      PATH: '/mypage/order/case?type=payment',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: '',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: '',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: '',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '비대면 반품',
      '2Depth': '목록',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/claims/remotereturn',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: '',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '과거 주문내역 조회',
      '2Depth': '목록',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/history',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '더현대 주문/배송 조회',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/history/thehyundai',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '현대식품관 to Home 주문/배송 조회',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/history/tohome',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '과거 주문 내역 조회(비로그인)',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/history/guest',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: '',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: '',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: '',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: '',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: '',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '쇼핑혜택',
      '2Depth': '마이바우처',
      '3Depth': '바우처',
      '4Depth': '사용가능',
      FILE: '/mypage/myvoucher/MyVoucher',
      PATH: '/mypage/voucher',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '사용완료/만료/취소',
      FILE: '/mypage/myvoucher/MyVoucher',
      PATH: '/mypage/voucher?tab2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'Nodata',
      FILE: '/mypage/myvoucher/MyVoucher',
      PATH: '/mypage/voucher?nodata',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 바우처 사용하기 (D)',
      FILE: '/mypage/myvoucher/UseVoucherDrawer',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 직원확인 하기-아이체크 방식 (D)',
      FILE: '/mypage/myvoucher/EmployeeCheckDrawer',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 직원확인 하기-아이체크 방식+수량선택 (D)',
      FILE: '/mypage/myvoucher/EmployeeCheckDrawer',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 쿠폰 비밀번호 입력: 인증키 방식 (D)',
      FILE: '/mypage/myvoucher/CouponPasswordDrawer',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 쿠폰 비밀번호 입력: 인증키 방식+수량선택 (D)',
      FILE: '/mypage/myvoucher/CouponPasswordDrawer',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'H.Point',
      '3Depth': '메인',
      '4Depth': '',
      FILE: '/mypage/point/HPointMain',
      PATH: '/mypage/hpoint',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '2025-07-28',
      비고: '설계수정반영',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'NoData',
      FILE: '/mypage/point/HPointMain',
      PATH: '/mypage/hpoint?nodata',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '소멸예정 포인트',
      '4Depth': '',
      FILE: '/mypage/point/HPointExpiring',
      PATH: '/mypage/hpoint/expiring',
      작업자: '채은미',
      상태: 'removed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '삭제됨',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'NoData',
      FILE: '/mypage/point/HPointExpiring',
      PATH: '/mypage/hpoint/expiring?nodata',
      작업자: '채은미',
      상태: 'removed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '삭제됨',
    },
    {
      '1Depth': '',
      '2Depth': 'RSVP 포인트',
      '3Depth': '메인',
      '4Depth': '',
      FILE: '/mypage/point/RsvpMain',
      PATH: '/mypage/rsvp',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'Nodata',
      FILE: '/mypage/point/RsvpMain',
      PATH: '/mypage/rsvp?nodata',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '소멸예정 포인트',
      '4Depth': '',
      FILE: '/mypage/point/RsvpExpiring',
      PATH: '/mypage/rsvp/expiring',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'Nodata',
      FILE: '/mypage/point/RsvpExpiring',
      PATH: '/mypage/rsvp/expiring?nodata',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '예치금',
      '3Depth': '메인',
      '4Depth': '',
      FILE: '/mypage/deposit/DepositMain',
      PATH: '/mypage/deposit',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'noData',
      FILE: '/mypage/deposit/DepositMain',
      PATH: '/mypage/deposit?nodata',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'HiHi 멤버십 관리',
      '3Depth': '[HiHi 멤버십 미가입자]',
      '4Depth': '',
      FILE: '/mypage/membership/MembershipInfo',
      PATH: '/mypage/membership/manage/info',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[HiHi 멤버십 가입 후 메인]',
      '4Depth': '이용권 변경 시',
      FILE: '/mypage/membership/MemberShipManage',
      PATH: '/mypage/membership/manage',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '해지 예약시',
      FILE: '/mypage/membership/MemberShipManage',
      PATH: '/mypage/membership/manage?case2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '멤버십 결제 현황',
      '4Depth': '멤버십 이용중',
      FILE: '/mypage/membership/PaymentStatus',
      PATH: '/mypage/membership/manage/payment',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '해지 예약중_이용기간 남음',
      FILE: '/mypage/membership/PaymentStatus',
      PATH: '/mypage/membership/manage/payment?case2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '이용 중단- 미납 3회차까지',
      FILE: '/mypage/membership/payment/PaymentStatus',
      PATH: '/mypage/membership/manage/payment?case3',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 결제수단 변경 (L)',
      FILE: '/mypage/membership/payment/PaymentChangeDialog',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '멤버십 변경 신청',
      '4Depth': '프라임 변경 시',
      FILE: '/mypage/membership/change/ChangePrime',
      PATH: '/mypage/membership/manage/change?status=status1',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '플러스 변경 시',
      FILE: '/mypage/membership/change/ChangePlus',
      PATH: '/mypage/membership/manage/change?status=status2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 정기배송 상품 변경 신청 (L)',
      FILE: '/mypage/membership/change/ProductChangeDialog',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '2025-07-28',
      비고: '설계변경반영',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '이용 내역 상세보기',
      '4Depth': '',
      FILE: '/mypage/membership/MembershipHistory',
      PATH: '/mypage/membership/manage/history',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'HiHi 멤버십 가입',
      '3Depth': '[프라임 선택 시]',
      '4Depth': '',
      FILE: '/mypage/membership/MembershipJoin',
      PATH: '/mypage/membership/join',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 가입 완료 (L)',
      '4Depth': '',
      FILE: '/mypage/membership/components/JoinCompleteDialog',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 가입 실패 (L)',
      '4Depth': '',
      FILE: '/mypage/membership/components/JoinFailDialog',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'HiHi 멤버십 해지',
      '3Depth': '[플러스 이용 해지하기 선택 시 플러스 혜택]',
      '4Depth': '',
      FILE: '/mypage/membership/cancel/CancelStep1',
      PATH: '/mypage/membership/cancel?status=status1&type=plus',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[프라임 이용 해지하기 선택 시 프라임 혜택]',
      '4Depth': '',
      FILE: '/mypage/membership/cancel/CancelStep1',
      PATH: '/mypage/membership/cancel?status=status1&type=prime',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[해지하기 선택 시]',
      '4Depth': '',
      FILE: '/mypage/membership/CancelStep2',
      PATH: '/mypage/membership/cancel?status=status2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '직접 입력 메시지 등록',
      FILE: '/mypage/membership/cancel/CancelReasonDrawer',
      PATH: '/mypage/membership/cancel?status=status2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '⤷ 해지 완료 (L)',
      '4Depth': '',
      FILE: '/mypage/membership/cancel/CancelCompleteDialog',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '클럽',
      '3Depth': '[case1. 클럽 미가입]',
      '4Depth': '',
      FILE: '/mypage/club/ClubMain',
      PATH: '/mypage/club',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[case2. 클럽 가입]',
      '4Depth': '',
      FILE: '/mypage/club/ClubMain',
      PATH: '/mypage/club?case2',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[case3. 클럽 가입불가]',
      '4Depth': '',
      FILE: '/mypage/club/ClubMain',
      PATH: '/mypage/club?case3',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '마이클럽',
      '3Depth': '클럽뷰티',
      '4Depth': '가입 현황',
      FILE: '/mypage/club/myclub/MyClubMain',
      PATH: '/mypage/club/myclub',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '가입',
      FILE: '/mypage/club/myclub/MyClubJoin',
      PATH: '/mypage/club/myclub/join?club=beauty',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '관심정보 수정',
      FILE: '/mypage/club/myclub/MyClubEdit',
      PATH: '/mypage/club/myclub/edit?club=beauty',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽맘스',
      '4Depth': '가입 현황 (작성가능한리뷰 없음 case)',
      FILE: '/mypage/club/myclub/MyClubMain',
      PATH: '/mypage/club/myclub?club=moms',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '가입',
      FILE: '/mypage/club/myclub/MyClubJoin',
      PATH: '/mypage/club/myclub/join?club=moms',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '관심정보 수정',
      FILE: '/mypage/club/myclub/MyClubEdit',
      PATH: '/mypage/club/myclub/edit?club=moms',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽아웃도어',
      '4Depth': '가입 현황',
      FILE: '/mypage/club/myclub/MyClubMain',
      PATH: '/mypage/club/myclub?club=outdoor',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '가입',
      FILE: '/mypage/club/myclub/MyClubJoin',
      PATH: '/mypage/club/myclub/join?club=outdoor',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '관심정보 수정',
      FILE: '/mypage/club/myclub/MyClubEdit',
      PATH: '/mypage/club/myclub/edit?club=outdoor',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽펫',
      '4Depth': '가입 현황',
      FILE: '/mypage/club/myclub/MyClubMain',
      PATH: '/mypage/club/myclub?club=pet',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '가입',
      FILE: '/mypage/club/myclub/MyClubJoin',
      PATH: '/mypage/club/myclub/join?club=pet',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '관심정보 수정',
      FILE: '/mypage/club/myclub/MyClubEdit',
      PATH: '/mypage/club/myclub/edit?club=pet',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽헬시',
      '4Depth': '가입 현황',
      FILE: '/mypage/club/myclub/MyClubMain',
      PATH: '/mypage/club/myclub?club=healthy',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '가입',
      FILE: '/mypage/club/myclub/MyClubJoin',
      PATH: '/mypage/club/myclub/join?club=healthy',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '관심정보 수정',
      FILE: '/mypage/club/myclub/MyClubEdit',
      PATH: '/mypage/club/myclub/edit?club=healthy',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽모던',
      '4Depth': '가입 현황',
      FILE: '/mypage/club/myclub/MyClubMain',
      PATH: '/mypage/club/myclub?club=modern',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '가입',
      FILE: '/mypage/club/myclub/MyClubJoin',
      PATH: '/mypage/club/myclub/join?club=modern',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '관심정보 수정',
      FILE: '/mypage/club/myclub/MyClubEdit',
      PATH: '/mypage/club/myclub/edit?club=modern',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽이지웰',
      '4Depth': '가입 현황',
      FILE: '/mypage/club/myclub/MyClubMain',
      PATH: '/mypage/club/myclub?club=ezwel',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽프렌즈',
      '4Depth': '가입 현황',
      FILE: '/mypage/club/myclub/MyClubMain',
      PATH: '/mypage/club/myclub?club=friends',
      작업자: '채은미',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '쿠폰',
      '3Depth': '보유 쿠폰',
      '4Depth': '',
      FILE: '/mypage/coupon/OwnedCouponList.tsx',
      PATH: '/mypage/coupon/owned',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '사용가능한 쿠폰 없는 경우',
      FILE: '/mypage/coupon/OwnedCouponList.tsx',
      PATH: '/mypage/coupon/owned?status=empty',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 쿠폰 등록하기(D)',
      FILE: '/widgets/coupon/AddCouponDrawer.tsx',
      PATH: '/mypage/coupon/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '다운 가능 쿠폰',
      '4Depth': '',
      FILE: '/mypage/coupon/DownloadableCouponList.tsx',
      PATH: '/mypage/coupon/download',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '사용가능한 쿠폰 없는 경우',
      FILE: '/mypage/coupon/DownloadableCouponList.tsx',
      PATH: '/mypage/coupon/download?status=empty',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '쿠폰 상세(온라인)',
      '4Depth': '쿠폰 적용 대상 (L)',
      FILE: '/widgets/coupon/ApplyCouponTargetDialog.tsx',
      PATH: '/mypage/coupon/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '주차권	[case1. 사용차량번호 미등록한 경우]',
      FILE: '/mypage/coupon/detail/online/parking/ParkingTicketForm.tsx',
      PATH: '/mypage/coupon/detail/parking?status=register',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '주차권 [case2. 차량번호 등록한 경우]',
      FILE: '/mypage/coupon/detail/online/parking/ParkingTicketForm.tsx',
      PATH: '/mypage/coupon/detail/parking?status=use',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '쿠폰 상세(오프라인)',
      '4Depth': '외부 제휴 이벤트',
      FILE: '/mypage/coupon/detail/offline/event/PartnerEventForm.tsx',
      PATH: '	/mypage/coupon/detail/event',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '쿠폰 사용하기',
      FILE: '/widgets/coupon/CouponUseDrawer.tsx',
      PATH: '/mypage/coupon/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 바코드형 (D)',
      FILE: '/widgets/coupon/CouponUseDrawer.tsx',
      PATH: '/mypage/coupon/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 인증키형 (D)',
      FILE: '/widgets/coupon/CouponUseDrawer.tsx',
      PATH: '/mypage/coupon/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '⤷ 아이체크/직원 확인형 (D)',
      FILE: '/widgets/coupon/CouponUseDrawer.tsx',
      PATH: '/mypage/coupon/etc',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '사용 확인 완료',
      FILE: '/mypage/coupon/detail/offline/complete/UseCompleteForm.tsx',
      PATH: '	/mypage/coupon/detail/complete',
      작업자: '정지우',
      상태: 'completed',
      완료일: '2025-07-18',
      최종수정일: '',
      비고: '',
    },
  ],
} as const;

export default mypage;
