const mypage = {
  pages: [
    {
      '1Depth': '팝업모음집',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/etc',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '주문 버튼 케이스',
      '2Depth': '공통',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/btns?type=common',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '스토어픽',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/btns?type=storepick',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '선물하기',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/btns?type=gift',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '방문픽업',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/btns?type=pickup',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '체험단/0원상품',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/btns?type=experience',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '기타',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/btns?type=etc',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '취소 가능 케이스',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/btns?type=cancelable',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '문화센터 예외',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/btns?type=culture',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: '',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '주문/배송',
      '2Depth': '목록',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/list',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '결과없음',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/list?nodata',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '영수증',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/receipt',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: '',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '상세',
      '3Depth': '일반',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/normal',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '일반 - 멀티',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/normal/multi',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '스토어픽',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/storepick',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '선물하기',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/gift',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '선물하기 - 멀티',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/gift/multi',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '역직구_EMS',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/global/export',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '직구',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/global/import',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '렌탈',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/rental',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '명절배송',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/holiday',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '체험단',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/experience',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '문화센터',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/culture',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '방문픽업',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/visit',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '사은품 - 0원상품',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/detail/purchasegift',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[컴퍼넌트 케이스]',
      '4Depth': '결제수단 & 승인내역',
      FILE: '',
      PATH: '/mypage/order/case?type=paymentApproval',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '결제정보',
      FILE: '',
      PATH: '/mypage/order/case?type=payment',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: '',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '비대면 반품',
      '2Depth': '목록',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/claims/remotereturn',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: '',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '과거 주문내역 조회',
      '2Depth': '목록',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/history',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '더현대 주문/배송 조회',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/history/thehyundai',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '현대식품관 to Home 주문/배송 조회',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/history/tohome',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '과거 주문 내역 조회(비로그인)',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/order/history/guest',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: '',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: '',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: '',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: '',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '',
      작업자: '',
      상태: '',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
  ],
} as const;

export default mypage;
