const mypage = {
  pages: [
    {
      '1Depth': '팝업모음집',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '쇼핑혜택',
      '2Depth': '마이바우처',
      '3Depth': '바우처',
      '4Depth': '사용가능',
      FILE: '',
      PATH: '/mypage/voucher',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '사용완료/만료/취소',
      FILE: '',
      PATH: '/mypage/voucher?tab2',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'Nodata',
      FILE: '',
      PATH: '/mypage/voucher?nodata',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'H.Point',
      '3Depth': '메인',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/hpoint',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'NoData',
      FILE: '',
      PATH: '/mypage/hpoint?nodata',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '소멸예정 포인트',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/hpoint/expiring',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'NoData',
      FILE: '',
      PATH: '/mypage/hpoint/expiring?nodata',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '예치금',
      '3Depth': '메인',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/deposit',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'noData',
      FILE: '',
      PATH: '/mypage/deposit?nodata',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'RSVP 포인트',
      '3Depth': '메인',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/rsvp',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'Nodata',
      FILE: '',
      PATH: '/mypage/rsvp?noda',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '소멸예정 포인트',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/rsvp/expiring',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': 'Nodata',
      FILE: '',
      PATH: '/mypage/rsvp/expiring?nodata',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'HiHi 멤버십 관리',
      '3Depth': '[HiHi 멤버십 미가입자]',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/membership/manage/info',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[HiHi 멤버십 가입 후 메인]',
      '4Depth': '이용권 변경 시',
      FILE: '',
      PATH: '/mypage/membership/manage',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '해지 예약시',
      FILE: '',
      PATH: '/mypage/membership/manage?case2',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '멤버십 결제 현황',
      '4Depth': '멤버십 이용중',
      FILE: '',
      PATH: '/mypage/membership/manage/payment',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '해지 예약중_이용기간 남음',
      FILE: '',
      PATH: '/mypage/membership/manage/payment?case2',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '이용 중단- 미납 3회차까지',
      FILE: '',
      PATH: '/mypage/membership/manage/payment?case3',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '멤버십 변경 신청',
      '4Depth': '프라임 변경 시',
      FILE: '',
      PATH: '/mypage/membership/manage/change?status=status1',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '플러스 변경 시',
      FILE: '',
      PATH: '/mypage/membership/manage/change?status=status2',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '이용 내역 상세보기',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/membership/manage/history',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'HiHi 멤버십 가입',
      '3Depth': '[프라임 선택 시]',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/membership/join',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[가입 성공]',
      '4Depth': '',
      FILE: 'mypage/membership/components/JoinCompleteDialog',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[가입 실패]',
      '4Depth': '',
      FILE: 'mypage/membership/components/JoinFailDialog',
      PATH: '/mypage/etc',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': 'HiHi 멤버십 해지',
      '3Depth': '[플러스 이용 해지하기 선택 시 플러스 혜택]',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/membership/cancel?status=status1&type=plus',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[프라임 이용 해지하기 선택 시 프라임 혜택]',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/membership/cancel?status=status1&type=prime',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[해지하기 선택 시]',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/membership/cancel?status=status2',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '직접 입력 메시지 등록',
      FILE: 'mypage/membership/cancel/CancelReasonDrawer',
      PATH: '/mypage/membership/cancel?status=status2',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': 'HiHi 멤버십 해지 완료',
      '4Depth': '',
      FILE: 'mypage/membership/cancel/CancelCompleteDialog',
      PATH: '	/mypage/etc',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '클럽',
      '3Depth': '[case1. 클럽 미가입]',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/club',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[case2. 클럽 가입]',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/club?case2',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '[case3. 클럽 가입불가]',
      '4Depth': '',
      FILE: '',
      PATH: '/mypage/club?case3',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '마이클럽',
      '3Depth': '클럽뷰티',
      '4Depth': '가입 현황',
      FILE: '',
      PATH: '/mypage/club/myclub',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '가입',
      FILE: '',
      PATH: '/mypage/club/myclub/join?club=beauty',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '관심정보 수정',
      FILE: '',
      PATH: '/mypage/club/myclub/edit?club=beauty',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽맘스',
      '4Depth': '가입 현황',
      FILE: '',
      PATH: '/mypage/club/myclub?club=moms',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '가입',
      FILE: '',
      PATH: '/mypage/club/myclub/join?club=moms',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '관심정보 수정',
      FILE: '',
      PATH: '/mypage/club/myclub/edit?club=moms',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽아웃도어',
      '4Depth': '가입 현황',
      FILE: '',
      PATH: '/mypage/club/myclub?club=outdoor',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '가입',
      FILE: '',
      PATH: '/mypage/club/myclub/join?club=outdoor',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '관심정보 수정',
      FILE: '',
      PATH: '/mypage/club/myclub/edit?club=outdoor',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽펫',
      '4Depth': '가입 현황',
      FILE: '',
      PATH: '/mypage/club/myclub?club=pet',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '가입',
      FILE: '',
      PATH: '/mypage/club/myclub/join?club=pet',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '관심정보 수정',
      FILE: '',
      PATH: '/mypage/club/myclub/edit?club=pet',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽헬시',
      '4Depth': '가입 현황',
      FILE: '',
      PATH: '/mypage/club/myclub?club=healthy',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '가입',
      FILE: '',
      PATH: '/mypage/club/myclub/join?club=healthy',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '관심정보 수정',
      FILE: '',
      PATH: '/mypage/club/myclub/edit?club=healthy',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽모던',
      '4Depth': '가입 현황',
      FILE: '',
      PATH: '/mypage/club/myclub?club=modern',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '가입',
      FILE: '',
      PATH: '/mypage/club/myclub/join?club=modern',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '',
      '4Depth': '관심정보 수정',
      FILE: '',
      PATH: '/mypage/club/myclub/edit?club=modern',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽이지웰',
      '4Depth': '가입 현황',
      FILE: '',
      PATH: '/mypage/club/myclub?club=ezwel',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      '1Depth': '',
      '2Depth': '',
      '3Depth': '클럽프렌즈',
      '4Depth': '가입 현황',
      FILE: '',
      PATH: '/mypage/club/myclub?club=friends',
      작업자: '채은미',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
  ],
} as const;

export default mypage;
